#[cfg(not(target_os = "ios"))]
use notify::{Config, Event, EventKind, RecommendedWatcher, RecursiveMode, Watcher};
use serde::{Deserialize, Serialize};
use std::env;
use std::{
    collections::{HashMap, HashSet},
    fs,
    path::{Path, PathBuf},
    sync::{
        atomic::{AtomicBool, Ordering},
        Mutex,
    },
    time::{SystemTime, UNIX_EPOCH},
};
#[cfg(not(target_os = "ios"))]
use tauri::menu::{Menu, MenuItem, PredefinedMenuItem, Submenu};
use tauri::{AppHandle, Emitter, Manager, State, Wry};
#[cfg(not(target_os = "ios"))]
use tauri::{Runtime, Url};
#[cfg(not(target_os = "ios"))]
use tauri_plugin_updater::{Updater, UpdaterExt};

#[cfg(not(target_os = "ios"))]
const RECENT_MENU_ID: &str = "file_open_recent";
#[cfg(not(target_os = "ios"))]
const RECENT_MENU_ITEM_PREFIX: &str = "file_recent_";
#[cfg(not(target_os = "ios"))]
const CLEAR_RECENT_MENU_ITEM_PREFIX: &str = "file_clear_recent_";
const RECENT_DOCUMENT_LIMIT: usize = 10;
const RECENT_DOCUMENTS_FILE_NAME: &str = "recent-documents.json";
const SETTINGS_FILE_NAME: &str = "settings.toml";
const DEFAULT_THEME: &str = "auto";
const DEFAULT_LOCAL_USER_NAME: &str = "Me";
#[cfg(not(target_os = "ios"))]
const UPDATER_ENDPOINT: &str =
    "https://github.com/soseinai/margin/releases/latest/download/latest.json";
#[cfg(not(target_os = "ios"))]
const UPDATER_PUBLIC_KEY: &str = "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDk3NTk2MUZGN0I5NzA0QzkKUldUSkJKZDcvMkZabHcrNXlvcEJFeFUxOHZ3TTI0ZnBsbDQxUzJ0cDFNNEs0SHV5QzVZMHpBTzYK";
#[cfg(target_os = "macos")]
const CLI_MARKER: &str = "# Generated by Margin. Safe to overwrite.";
#[cfg(target_os = "macos")]
const CLI_NAME: &str = "margin";

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct NativeMarkdownDocument {
    path: String,
    name: String,
    markdown: String,
}

#[cfg(not(target_os = "ios"))]
#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct NativeMarkdownDocumentChange {
    path: String,
}

#[derive(Deserialize, Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct RecentDocumentEntry {
    title: String,
    path: String,
    #[serde(default)]
    opened_at: u64,
}

#[derive(Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
struct AppSettings {
    #[serde(default = "default_theme")]
    theme: String,
    #[serde(default = "default_local_user_name")]
    local_user_name: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct AppUpdateMetadata {
    current_version: String,
    version: String,
    notes: Option<String>,
}

impl Default for AppSettings {
    fn default() -> Self {
        Self {
            theme: DEFAULT_THEME.to_string(),
            local_user_name: default_local_user_name(),
        }
    }
}

#[derive(Default)]
struct NativeOpenState {
    frontend_ready: AtomicBool,
    pending_urls: Mutex<Vec<String>>,
}

#[cfg(not(target_os = "ios"))]
#[derive(Default)]
struct WatchedDocumentState {
    watchers: Mutex<HashMap<String, RecommendedWatcher>>,
}

#[cfg(not(target_os = "ios"))]
#[derive(Default)]
struct RecentDocumentsMenuState {
    menu: Mutex<Option<Submenu<Wry>>>,
}

#[tauri::command]
fn take_pending_open_urls(state: State<NativeOpenState>) -> Vec<String> {
    state.frontend_ready.store(true, Ordering::SeqCst);

    let mut pending_urls = state
        .pending_urls
        .lock()
        .expect("pending open URL state poisoned");
    std::mem::take(&mut *pending_urls)
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn choose_markdown_document() -> Result<Option<NativeMarkdownDocument>, String> {
    let picked = rfd::FileDialog::new()
        .add_filter("Markdown Documents", &["md", "markdown", "txt"])
        .pick_file();

    picked
        .map(|path| read_markdown_document_from_path(&path))
        .transpose()
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn choose_markdown_document() -> Result<Option<NativeMarkdownDocument>, String> {
    Err(ios_file_picker_message())
}

#[tauri::command]
fn open_markdown_document(path: String) -> Result<NativeMarkdownDocument, String> {
    read_markdown_document_from_path(&PathBuf::from(path))
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn watch_markdown_document(
    app: AppHandle,
    state: State<WatchedDocumentState>,
    path: String,
) -> Result<(), String> {
    let path = PathBuf::from(path)
        .canonicalize()
        .map_err(|err| format!("Unable to watch document: {err}"))?;

    ensure_markdown_path(&path)?;

    let parent = path
        .parent()
        .ok_or_else(|| "Unable to watch document without a parent directory".to_string())?
        .to_path_buf();
    let key = path.to_string_lossy().to_string();
    let mut watchers = state
        .watchers
        .lock()
        .expect("watched document state poisoned");

    if watchers.contains_key(&key) {
        return Ok(());
    }

    let watched_path = path.clone();
    let watched_path_string = key.clone();
    let app_handle = app.clone();
    let mut watcher = RecommendedWatcher::new(
        move |result: notify::Result<Event>| match result {
            Ok(event) => {
                if should_emit_document_change(&event, &watched_path) {
                    let _ = app_handle.emit(
                        "margin://document-changed",
                        NativeMarkdownDocumentChange {
                            path: watched_path_string.clone(),
                        },
                    );
                }
            }
            Err(err) => eprintln!("Unable to watch Markdown document: {err}"),
        },
        Config::default(),
    )
    .map_err(|err| format!("Unable to watch {}: {err}", display_name(&path)))?;

    watcher
        .watch(&parent, RecursiveMode::NonRecursive)
        .map_err(|err| format!("Unable to watch {}: {err}", display_name(&path)))?;
    watchers.insert(key, watcher);

    Ok(())
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn watch_markdown_document(_path: String) -> Result<(), String> {
    Ok(())
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn choose_markdown_save_path(suggested_name: String) -> Result<Option<String>, String> {
    let suggested_name = if suggested_name.trim().is_empty() {
        "document.md"
    } else {
        suggested_name.trim()
    };

    Ok(rfd::FileDialog::new()
        .add_filter("Markdown Documents", &["md", "markdown", "txt"])
        .set_file_name(suggested_name)
        .save_file()
        .map(normalized_save_path)
        .map(|path| path.to_string_lossy().to_string()))
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn choose_markdown_save_path(_suggested_name: String) -> Result<Option<String>, String> {
    Err(ios_file_picker_message())
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn show_comment_context_menu(window: tauri::WebviewWindow, x: f64, y: f64) -> Result<(), String> {
    let add_comment = MenuItem::with_id(
        window.app_handle(),
        "context_add_comment",
        "Add Comment",
        true,
        Some("CmdOrCtrl+Alt+M"),
    )
    .map_err(|err| err.to_string())?;
    let menu =
        Menu::with_items(window.app_handle(), &[&add_comment]).map_err(|err| err.to_string())?;

    window
        .popup_menu_at(&menu, tauri::LogicalPosition::new(x, y))
        .map_err(|err| err.to_string())
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn show_comment_context_menu(_x: f64, _y: f64) -> Result<(), String> {
    Ok(())
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn confirm_close_tab(title: String) -> bool {
    let title = if title.trim().is_empty() {
        "this tab"
    } else {
        title.trim()
    };

    matches!(
        rfd::MessageDialog::new()
            .set_level(rfd::MessageLevel::Warning)
            .set_title("Close Tab?")
            .set_description(format!(
                "{title} has unsaved changes. If you close it now, those changes will be discarded."
            ))
            .set_buttons(rfd::MessageButtons::OkCancelCustom(
                "Discard and Close".to_string(),
                "Cancel".to_string(),
            ))
            .show(),
        rfd::MessageDialogResult::Custom(value) if value == "Discard and Close"
    )
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn confirm_close_tab(_title: String) -> bool {
    false
}

#[tauri::command]
fn quit_app(app: AppHandle) {
    app.exit(0);
}

#[tauri::command]
fn save_markdown_document(
    path: String,
    markdown: String,
) -> Result<NativeMarkdownDocument, String> {
    let path = normalized_save_path(PathBuf::from(path));
    ensure_markdown_path(&path)?;
    fs::write(&path, &markdown)
        .map_err(|err| format!("Unable to save {}: {err}", display_name(&path)))?;

    Ok(markdown_document_payload(&path, markdown))
}

#[tauri::command]
fn read_settings(app: AppHandle) -> Result<AppSettings, String> {
    read_settings_file(&app)
}

#[tauri::command]
fn write_settings(app: AppHandle, settings: AppSettings) -> Result<AppSettings, String> {
    let settings = AppSettings {
        theme: normalized_theme(&settings.theme).to_string(),
        local_user_name: normalized_local_user_name(&settings.local_user_name),
    };
    let path = settings_path(&app)?;

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("Unable to create settings directory: {err}"))?;
    }

    fs::write(&path, settings_toml(&settings))
        .map_err(|err| format!("Unable to write {}: {err}", display_name(&path)))?;

    Ok(settings)
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
async fn check_for_app_update(app: AppHandle) -> Result<Option<AppUpdateMetadata>, String> {
    let updater = app_updater(&app).map_err(|err| format!("Unable to check for updates: {err}"))?;
    let update = updater
        .check()
        .await
        .map_err(|err| format!("Unable to check for updates: {err}"))?;

    Ok(update.map(|update| AppUpdateMetadata {
        current_version: update.current_version,
        version: update.version,
        notes: update.body,
    }))
}

#[cfg(target_os = "ios")]
#[tauri::command]
async fn check_for_app_update() -> Result<Option<AppUpdateMetadata>, String> {
    Ok(None)
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
async fn install_app_update(app: AppHandle) -> Result<(), String> {
    #[cfg(target_os = "macos")]
    ensure_macos_app_update_location()?;

    let updater = app_updater(&app).map_err(|err| format!("Unable to install update: {err}"))?;
    let Some(update) = updater
        .check()
        .await
        .map_err(|err| format!("Unable to install update: {err}"))?
    else {
        return Err("No update is available.".to_string());
    };

    update
        .download_and_install(|_, _| {}, || {})
        .await
        .map_err(|err| format!("Unable to install update: {err}"))?;
    app.restart();
}

#[cfg(target_os = "ios")]
#[tauri::command]
async fn install_app_update() -> Result<(), String> {
    Err("App updates are not available on iOS.".to_string())
}

#[tauri::command]
fn read_recent_documents(app: AppHandle) -> Result<Vec<RecentDocumentEntry>, String> {
    read_recent_documents_file(&app)
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn write_recent_documents(
    app: AppHandle,
    menu_state: State<RecentDocumentsMenuState>,
    entries: Vec<RecentDocumentEntry>,
) -> Result<Vec<RecentDocumentEntry>, String> {
    let entries = normalized_recent_documents(entries);

    write_recent_documents_file(&app, &entries)?;
    update_recent_documents_menu(&app, &menu_state, &entries)?;

    Ok(entries)
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn write_recent_documents(
    app: AppHandle,
    entries: Vec<RecentDocumentEntry>,
) -> Result<Vec<RecentDocumentEntry>, String> {
    let entries = normalized_recent_documents(entries);

    write_recent_documents_file(&app, &entries)?;

    Ok(entries)
}

#[cfg(not(target_os = "ios"))]
fn set_recent_documents_menu_entries(
    app: &AppHandle,
    recent_menu: &Submenu<Wry>,
    entries: &[RecentDocumentEntry],
) -> Result<(), String> {
    clear_submenu(recent_menu)?;

    let nonce = recent_menu_nonce();

    if entries.is_empty() {
        let empty = MenuItem::with_id(
            app,
            format!("file_recent_empty_{nonce}"),
            "No Recent Documents",
            false,
            None::<&str>,
        )
        .map_err(|err| err.to_string())?;
        recent_menu.append(&empty).map_err(|err| err.to_string())?;
        return Ok(());
    }

    for (index, entry) in entries.iter().take(RECENT_DOCUMENT_LIMIT).enumerate() {
        let item = MenuItem::with_id(
            app,
            format!("{RECENT_MENU_ITEM_PREFIX}{nonce}_{index}"),
            recent_menu_label(&entry.title),
            true,
            None::<&str>,
        )
        .map_err(|err| err.to_string())?;
        recent_menu.append(&item).map_err(|err| err.to_string())?;
    }

    let separator = PredefinedMenuItem::separator(app).map_err(|err| err.to_string())?;
    let clear = MenuItem::with_id(
        app,
        format!("{CLEAR_RECENT_MENU_ITEM_PREFIX}{nonce}"),
        "Clear Menu",
        true,
        None::<&str>,
    )
    .map_err(|err| err.to_string())?;
    recent_menu
        .append_items(&[&separator, &clear])
        .map_err(|err| err.to_string())?;

    Ok(())
}

#[cfg(not(target_os = "ios"))]
fn update_recent_documents_menu(
    app: &AppHandle,
    menu_state: &State<RecentDocumentsMenuState>,
    entries: &[RecentDocumentEntry],
) -> Result<(), String> {
    let recent_menu = menu_state
        .menu
        .lock()
        .expect("recent documents menu state poisoned")
        .clone()
        .ok_or_else(|| "Recent documents menu is not available".to_string())?;

    set_recent_documents_menu_entries(app, &recent_menu, entries)
}

#[cfg(not(target_os = "ios"))]
fn app_updater(app: &AppHandle) -> Result<Updater, tauri_plugin_updater::Error> {
    app.updater_builder()
        .pubkey(UPDATER_PUBLIC_KEY)
        .endpoints(vec![UPDATER_ENDPOINT.parse()?])?
        .build()
}

#[cfg(target_os = "macos")]
fn ensure_macos_app_update_location() -> Result<(), String> {
    const NO_SUCH_FILE_ERROR: i32 = 2;
    const READ_ONLY_FILESYSTEM_ERROR: i32 = 30;

    let Some(app_bundle_path) = current_macos_app_bundle_path()? else {
        return Ok(());
    };
    if is_transient_macos_app_location(&app_bundle_path) {
        return Err(macos_update_location_error(&app_bundle_path));
    }

    let Some(parent) = app_bundle_path.parent() else {
        return Ok(());
    };

    let probe_path = parent.join(format!(".margin-update-write-test-{}", std::process::id()));

    match fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&probe_path)
    {
        Ok(_) => {
            let _ = fs::remove_file(&probe_path);
            Ok(())
        }
        Err(err)
            if matches!(
                err.raw_os_error(),
                Some(NO_SUCH_FILE_ERROR | READ_ONLY_FILESYSTEM_ERROR)
            ) =>
        {
            Err(macos_update_location_error(&app_bundle_path))
        }
        Err(_) => Ok(()),
    }
}

#[cfg(target_os = "macos")]
fn current_macos_app_bundle_path() -> Result<Option<PathBuf>, String> {
    let executable_path =
        env::current_exe().map_err(|err| format!("Unable to locate the running app: {err}"))?;

    Ok(macos_app_bundle_path_from_executable(&executable_path))
}

#[cfg(target_os = "macos")]
fn macos_app_bundle_path_from_executable(executable_path: &Path) -> Option<PathBuf> {
    executable_path
        .ancestors()
        .find(|path| path.extension().and_then(|extension| extension.to_str()) == Some("app"))
        .map(PathBuf::from)
}

#[cfg(target_os = "macos")]
fn is_transient_macos_app_location(app_bundle_path: &Path) -> bool {
    app_bundle_path.starts_with("/Volumes")
}

#[cfg(target_os = "macos")]
fn macos_update_location_error(app_bundle_path: &Path) -> String {
    format!(
        "Margin is running from a location that cannot be updated in place: {}. Drag Margin to Applications, quit this copy, reopen /Applications/Margin.app, then install the update.",
        app_bundle_path.display()
    )
}

#[cfg(not(target_os = "ios"))]
fn show_cli_install_result(result: Result<PathBuf, String>) {
    match result {
        Ok(path) => {
            let _ = rfd::MessageDialog::new()
                .set_level(rfd::MessageLevel::Info)
                .set_title("Command Installed")
                .set_description(format!(
                    "Installed the margin command at {}.\n\nNote: make sure ~/.local/bin is in your PATH",
                    path.display()
                ))
                .set_buttons(rfd::MessageButtons::Ok)
                .show();
        }
        Err(err) => {
            let _ = rfd::MessageDialog::new()
                .set_level(rfd::MessageLevel::Error)
                .set_title("Unable to Install Command")
                .set_description(err)
                .set_buttons(rfd::MessageButtons::Ok)
                .show();
        }
    }
}

#[cfg(target_os = "macos")]
fn install_margin_cli() -> Result<PathBuf, String> {
    let app_bundle_path = current_macos_app_bundle_path()?;

    if let Some(app_bundle_path) = &app_bundle_path {
        if is_transient_macos_app_location(app_bundle_path) {
            return Err(format!(
                "Margin is running from {}. Drag Margin to Applications, quit this copy, reopen /Applications/Margin.app, then install the command again.",
                app_bundle_path.display()
            ));
        }
    }

    let destination = margin_cli_destination()?;
    let script = margin_cli_script(app_bundle_path.as_deref());

    write_executable_file(&destination, &script)?;

    Ok(destination)
}

#[cfg(all(not(target_os = "macos"), not(target_os = "ios")))]
fn install_margin_cli() -> Result<PathBuf, String> {
    Err("The margin command installer is currently only available on macOS.".to_string())
}

#[cfg(target_os = "macos")]
fn margin_cli_destination() -> Result<PathBuf, String> {
    let destination = margin_cli_destination_candidate()?;

    if destination.exists() {
        if existing_margin_cli(&destination)? {
            ensure_writable_destination(&destination)?;
            return Ok(destination);
        }

        return Err(format!(
            "A different command already exists at {}. Move or rename that command before installing Margin's CLI.",
            destination.display()
        ));
    }

    ensure_writable_destination(&destination)?;

    Ok(destination)
}

#[cfg(target_os = "macos")]
fn margin_cli_destination_candidate() -> Result<PathBuf, String> {
    env::var_os("HOME")
        .map(|home| {
            PathBuf::from(home)
                .join(".local")
                .join("bin")
                .join(CLI_NAME)
        })
        .ok_or_else(|| {
            "Margin could not locate your home directory to install ~/.local/bin/margin."
                .to_string()
        })
}

#[cfg(target_os = "macos")]
fn existing_margin_cli(path: &Path) -> Result<bool, String> {
    if !path.is_file() {
        return Ok(false);
    }

    let contents = fs::read(path).map_err(|err| {
        format!(
            "Unable to inspect existing command at {}: {err}",
            path.display()
        )
    })?;

    Ok(contents
        .windows(CLI_MARKER.len())
        .any(|window| window == CLI_MARKER.as_bytes()))
}

#[cfg(target_os = "macos")]
fn ensure_writable_destination(path: &Path) -> Result<(), String> {
    let parent = path.parent().ok_or_else(|| {
        format!(
            "Unable to locate the parent directory for {}",
            path.display()
        )
    })?;

    fs::create_dir_all(parent)
        .map_err(|err| format!("Unable to create {}: {err}", parent.display()))?;

    let probe_path = parent.join(format!(".margin-cli-install-probe-{}", std::process::id()));

    match fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&probe_path)
    {
        Ok(_) => {
            let _ = fs::remove_file(&probe_path);
            Ok(())
        }
        Err(err) => Err(format!("Unable to write to {}: {err}", parent.display())),
    }
}

#[cfg(target_os = "macos")]
fn write_executable_file(path: &Path, contents: &str) -> Result<(), String> {
    use std::os::unix::fs::PermissionsExt;

    let parent = path.parent().ok_or_else(|| {
        format!(
            "Unable to locate the parent directory for {}",
            path.display()
        )
    })?;
    let temporary_path = parent.join(format!(".margin-cli-install-{}", std::process::id()));

    fs::write(&temporary_path, contents)
        .map_err(|err| format!("Unable to write {}: {err}", temporary_path.display()))?;
    fs::set_permissions(&temporary_path, fs::Permissions::from_mode(0o755)).map_err(|err| {
        format!(
            "Unable to make {} executable: {err}",
            temporary_path.display()
        )
    })?;
    if let Err(err) = fs::rename(&temporary_path, path) {
        let _ = fs::remove_file(&temporary_path);

        return Err(format!("Unable to install {}: {err}", path.display()));
    }

    Ok(())
}

#[cfg(target_os = "macos")]
fn margin_cli_script(app_bundle_path: Option<&Path>) -> String {
    let app_bundle = app_bundle_path
        .map(shell_single_quoted)
        .unwrap_or_else(|| "''".to_string());

    format!(
        r#"#!/bin/zsh
{CLI_MARKER}
set -e

app_bundle={app_bundle}

args=()
for arg in "$@"; do
  case "$arg" in
    margin://*|file://*|/*)
      args+=("$arg")
      ;;
    *)
      args+=("$PWD/$arg")
      ;;
  esac
done

if [[ -n "$app_bundle" && -d "$app_bundle" ]]; then
  exec open -n "$app_bundle" --args "${{args[@]}}"
fi

exec open -n -a "Margin" --args "${{args[@]}}"
"#
    )
}

#[cfg(target_os = "macos")]
fn shell_single_quoted(value: &Path) -> String {
    let value = value.to_string_lossy();
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(all(test, target_os = "macos"))]
mod tests {
    use super::*;

    #[test]
    fn finds_macos_app_bundle_from_executable_path() {
        let executable_path = Path::new("/Applications/Margin.app/Contents/MacOS/margin-desktop");

        assert_eq!(
            macos_app_bundle_path_from_executable(executable_path),
            Some(PathBuf::from("/Applications/Margin.app"))
        );
    }

    #[test]
    fn ignores_executable_paths_outside_app_bundles() {
        let executable_path = Path::new("/usr/local/bin/margin-desktop");

        assert_eq!(macos_app_bundle_path_from_executable(executable_path), None);
    }

    #[test]
    fn treats_apps_launched_from_mounted_volumes_as_transient() {
        assert!(is_transient_macos_app_location(Path::new(
            "/Volumes/Margin/Margin.app"
        )));
        assert!(!is_transient_macos_app_location(Path::new(
            "/Applications/Margin.app"
        )));
    }

    #[test]
    fn update_location_error_points_user_to_applications_copy() {
        let message = macos_update_location_error(Path::new("/Volumes/Margin/Margin.app"));

        assert!(message.contains("/Volumes/Margin/Margin.app"));
        assert!(message.contains("/Applications/Margin.app"));
    }

    #[test]
    fn cli_script_opens_current_app_bundle_with_arguments() {
        let script = margin_cli_script(Some(Path::new("/Applications/Margin.app")));

        assert!(script.contains(CLI_MARKER));
        assert!(script.contains("app_bundle='/Applications/Margin.app'"));
        assert!(script.contains("exec open -n \"$app_bundle\" --args \"${args[@]}\""));
        assert!(script.contains("args+=(\"$PWD/$arg\")"));
    }

    #[test]
    fn shell_quotes_app_bundle_paths() {
        assert_eq!(
            shell_single_quoted(Path::new("/Applications/Margin's App.app")),
            "'/Applications/Margin'\\''s App.app'"
        );
    }
}

#[cfg(target_os = "ios")]
fn ios_file_picker_message() -> String {
    "Native document picking is not available in the iOS preview yet.".to_string()
}

fn read_settings_file(app: &AppHandle) -> Result<AppSettings, String> {
    let path = settings_path(app)?;
    if !path.exists() {
        return Ok(AppSettings::default());
    }

    let contents = fs::read_to_string(&path)
        .map_err(|err| format!("Unable to read {}: {err}", display_name(&path)))?;
    Ok(parse_settings_toml(&contents))
}

fn settings_path(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(app
        .path()
        .app_config_dir()
        .map_err(|err| format!("Unable to locate app config directory: {err}"))?
        .join(SETTINGS_FILE_NAME))
}

fn recent_documents_path(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(app_state_dir(app)?.join(RECENT_DOCUMENTS_FILE_NAME))
}

fn app_state_dir(app: &AppHandle) -> Result<PathBuf, String> {
    #[cfg(target_os = "linux")]
    {
        linux_app_state_dir(app)
    }

    #[cfg(not(target_os = "linux"))]
    {
        app.path()
            .app_data_dir()
            .map_err(|err| format!("Unable to locate app data directory: {err}"))
    }
}

#[cfg(target_os = "linux")]
fn linux_app_state_dir(app: &AppHandle) -> Result<PathBuf, String> {
    if let Some(path) = env::var_os("XDG_STATE_HOME").map(PathBuf::from) {
        if path.is_absolute() {
            return Ok(path.join(&app.config().identifier));
        }
    }

    env::var_os("HOME")
        .map(PathBuf::from)
        .map(|home| {
            home.join(".local")
                .join("state")
                .join(&app.config().identifier)
        })
        .ok_or_else(|| "Unable to locate home directory for app state".to_string())
}

fn parse_settings_toml(contents: &str) -> AppSettings {
    let mut settings = AppSettings::default();

    for line in contents.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let Some((key, value)) = line.split_once('=') else {
            continue;
        };

        let value = settings_value(value);

        match key.trim() {
            "theme" => settings.theme = normalized_theme(&value).to_string(),
            "local_user_name" | "localUserName" => {
                settings.local_user_name = normalized_local_user_name(&value);
            }
            _ => {}
        }
    }

    settings
}

fn settings_toml(settings: &AppSettings) -> String {
    format!(
        "theme = {}\nlocal_user_name = {}\n",
        toml_string_literal(normalized_theme(&settings.theme)),
        toml_string_literal(&normalized_local_user_name(&settings.local_user_name))
    )
}

fn default_theme() -> String {
    DEFAULT_THEME.to_string()
}

fn normalized_theme(theme: &str) -> &'static str {
    match theme.trim().to_ascii_lowercase().as_str() {
        "light" => "light",
        "dark" => "dark",
        _ => DEFAULT_THEME,
    }
}

fn normalized_local_user_name(name: &str) -> String {
    cleaned_local_user_name(name).unwrap_or_else(default_local_user_name)
}

fn default_local_user_name() -> String {
    os_local_user_name().unwrap_or_else(|| DEFAULT_LOCAL_USER_NAME.to_string())
}

#[cfg(target_os = "windows")]
fn os_local_user_name() -> Option<String> {
    env::var("USERNAME")
        .ok()
        .and_then(|name| cleaned_local_user_name(&name))
}

#[cfg(not(target_os = "windows"))]
fn os_local_user_name() -> Option<String> {
    env::var("USER")
        .ok()
        .and_then(|name| cleaned_local_user_name(&name))
}

fn cleaned_local_user_name(name: &str) -> Option<String> {
    let name = name.split_whitespace().collect::<Vec<_>>().join(" ");

    if name.is_empty() {
        None
    } else {
        Some(name)
    }
}

fn settings_value(value: &str) -> String {
    let value = value.trim();

    if let Some(rest) = value.strip_prefix('"') {
        return quoted_settings_value(rest, '"', true);
    }

    if let Some(rest) = value.strip_prefix('\'') {
        return quoted_settings_value(rest, '\'', false);
    }

    value.split('#').next().unwrap_or("").trim().to_string()
}

fn quoted_settings_value(value: &str, quote: char, escaped: bool) -> String {
    let mut output = String::new();
    let mut chars = value.chars();

    while let Some(character) = chars.next() {
        if character == quote {
            break;
        }

        if escaped && character == '\\' {
            let Some(escaped_character) = chars.next() else {
                break;
            };

            output.push(match escaped_character {
                'n' => '\n',
                'r' => '\r',
                't' => '\t',
                '"' => '"',
                '\\' => '\\',
                other => other,
            });

            continue;
        }

        output.push(character);
    }

    output
}

fn toml_string_literal(value: &str) -> String {
    let mut output = String::from("\"");

    for character in value.chars() {
        match character {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            other => output.push(other),
        }
    }

    output.push('"');
    output
}

fn read_recent_documents_file(app: &AppHandle) -> Result<Vec<RecentDocumentEntry>, String> {
    let path = recent_documents_path(app)?;
    if !path.exists() {
        return Ok(Vec::new());
    }

    let contents = fs::read_to_string(&path)
        .map_err(|err| format!("Unable to read {}: {err}", display_name(&path)))?;
    let entries = serde_json::from_str::<Vec<RecentDocumentEntry>>(&contents)
        .map_err(|err| format!("Unable to parse {}: {err}", display_name(&path)))?;

    Ok(normalized_recent_documents(entries))
}

fn write_recent_documents_file(
    app: &AppHandle,
    entries: &[RecentDocumentEntry],
) -> Result<(), String> {
    let path = recent_documents_path(app)?;

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("Unable to create app data directory: {err}"))?;
    }

    let contents = serde_json::to_string_pretty(entries)
        .map_err(|err| format!("Unable to encode recent documents: {err}"))?;

    fs::write(&path, contents)
        .map_err(|err| format!("Unable to write {}: {err}", display_name(&path)))
}

fn normalized_recent_documents(entries: Vec<RecentDocumentEntry>) -> Vec<RecentDocumentEntry> {
    let mut seen_paths = HashSet::new();
    let mut normalized = Vec::new();

    for entry in entries {
        let path = entry.path.trim();

        if path.is_empty() || !seen_paths.insert(path.to_string()) {
            continue;
        }

        let title = if entry.title.trim().is_empty() {
            display_name(Path::new(path))
        } else {
            entry.title.trim().to_string()
        };

        normalized.push(RecentDocumentEntry {
            title,
            path: path.to_string(),
            opened_at: entry.opened_at,
        });

        if normalized.len() >= RECENT_DOCUMENT_LIMIT {
            break;
        }
    }

    normalized
}

fn read_markdown_document_from_path(path: &Path) -> Result<NativeMarkdownDocument, String> {
    ensure_markdown_path(path)?;
    let markdown = fs::read_to_string(path)
        .map_err(|err| format!("Unable to read {}: {err}", display_name(path)))?;
    Ok(markdown_document_payload(path, markdown))
}

#[cfg(not(target_os = "ios"))]
fn should_emit_document_change(event: &Event, watched_path: &Path) -> bool {
    let relevant_kind = matches!(
        &event.kind,
        EventKind::Any | EventKind::Create(_) | EventKind::Modify(_) | EventKind::Remove(_)
    );

    relevant_kind && event.paths.iter().any(|path| path == watched_path)
}

fn markdown_document_payload(path: &Path, markdown: String) -> NativeMarkdownDocument {
    let path = path.canonicalize().unwrap_or_else(|_| path.to_path_buf());

    NativeMarkdownDocument {
        name: display_name(&path),
        path: path.to_string_lossy().to_string(),
        markdown,
    }
}

fn ensure_markdown_path(path: &Path) -> Result<(), String> {
    if is_markdown_path(path) {
        Ok(())
    } else {
        Err("Margin can open Markdown, Markdown-like, or plain text documents.".to_string())
    }
}

fn normalized_save_path(mut path: PathBuf) -> PathBuf {
    if path.extension().is_none() {
        path.set_extension("md");
    }
    path
}

fn display_name(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("Untitled.md")
        .to_string()
}

#[cfg(not(target_os = "ios"))]
fn clear_submenu<R: Runtime>(menu: &Submenu<R>) -> Result<(), String> {
    let item_count = menu.items().map_err(|err| err.to_string())?.len();
    for index in (0..item_count).rev() {
        menu.remove_at(index).map_err(|err| err.to_string())?;
    }
    Ok(())
}

#[cfg(not(target_os = "ios"))]
fn recent_menu_label(title: &str) -> String {
    const MAX_CHARS: usize = 52;
    if title.chars().count() <= MAX_CHARS {
        return title.to_string();
    }

    let mut label = title.chars().take(MAX_CHARS - 1).collect::<String>();
    label.push_str("...");
    label
}

#[cfg(not(target_os = "ios"))]
fn recent_menu_nonce() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_nanos())
        .unwrap_or_default()
}

#[cfg(not(target_os = "ios"))]
fn recent_document_menu_index(menu_id: &str) -> Option<usize> {
    let suffix = menu_id.strip_prefix(RECENT_MENU_ITEM_PREFIX)?;

    let (nonce, index) = suffix.rsplit_once('_')?;

    if nonce.is_empty() || !nonce.chars().all(|character| character.is_ascii_digit()) {
        return None;
    }

    index.parse().ok()
}

fn dispatch_native_open_urls(app: &AppHandle, urls: Vec<String>) {
    if urls.is_empty() {
        return;
    }

    #[cfg(not(target_os = "ios"))]
    {
        if let Some(window) = app.get_webview_window("main") {
            let _ = window.show();
            let _ = window.set_focus();
        }
    }

    let state = app.state::<NativeOpenState>();
    if state.frontend_ready.load(Ordering::SeqCst) {
        let _ = app.emit("margin://open-urls", urls);
        return;
    }

    let mut pending_urls = state
        .pending_urls
        .lock()
        .expect("pending open URL state poisoned");
    pending_urls.extend(urls);
}

#[cfg(not(target_os = "ios"))]
fn launch_urls_from_args(args: Vec<String>) -> Vec<String> {
    args.into_iter()
        .skip(1)
        .filter_map(launch_url_from_arg)
        .collect()
}

#[cfg(not(target_os = "ios"))]
fn launch_url_from_arg(arg: String) -> Option<String> {
    if arg.starts_with("margin://") || arg.starts_with("file://") {
        return Some(arg);
    }

    let path = PathBuf::from(&arg);
    if !path.exists() || !is_markdown_path(&path) {
        return None;
    }

    Url::from_file_path(path).ok().map(|url| url.to_string())
}

fn is_markdown_path(path: &Path) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .map(|extension| {
            matches!(
                extension.to_ascii_lowercase().as_str(),
                "md" | "markdown" | "txt"
            )
        })
        .unwrap_or(false)
}

#[cfg(not(target_os = "ios"))]
fn insert_payload(menu_id: &str) -> Option<&'static str> {
    match menu_id {
        "insert_table" => Some("table"),
        "insert_tasks" => Some("tasks"),
        "insert_bullets" => Some("bullets"),
        "insert_numbers" => Some("numbers"),
        _ => None,
    }
}

#[cfg(not(target_os = "ios"))]
fn insert_menu_position() -> usize {
    #[cfg(target_os = "macos")]
    {
        3
    }
    #[cfg(any(
        target_os = "linux",
        target_os = "dragonfly",
        target_os = "freebsd",
        target_os = "netbsd",
        target_os = "openbsd"
    ))]
    {
        1
    }
    #[cfg(not(any(
        target_os = "macos",
        target_os = "linux",
        target_os = "dragonfly",
        target_os = "freebsd",
        target_os = "netbsd",
        target_os = "openbsd"
    )))]
    {
        2
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default()
        .manage(NativeOpenState::default())
        .plugin(tauri_plugin_deep_link::init());

    #[cfg(not(target_os = "ios"))]
    let builder = builder
        .manage(WatchedDocumentState::default())
        .manage(RecentDocumentsMenuState::default());

    #[cfg(not(target_os = "ios"))]
    let builder = builder.plugin(tauri_plugin_single_instance::init(|app, args, _cwd| {
        dispatch_native_open_urls(app, launch_urls_from_args(args));
    }));

    #[cfg(not(target_os = "ios"))]
    let builder = builder.plugin(
        tauri_plugin_updater::Builder::new()
            .pubkey(UPDATER_PUBLIC_KEY)
            .build(),
    );

    let builder = builder.setup(|app| {
        #[cfg(not(target_os = "ios"))]
        {
            let menu = Menu::default(app.handle())?;
            let settings_item = MenuItem::with_id(
                app,
                "app_settings",
                "Settings...",
                true,
                Some("CmdOrCtrl+,"),
            )?;
            let check_updates_item = MenuItem::with_id(
                app,
                "app_check_updates",
                "Check for Updates...",
                true,
                None::<&str>,
            )?;
            let install_cli_item = MenuItem::with_id(
                app,
                "app_install_cli",
                "Install 'margin' Command...",
                true,
                None::<&str>,
            )?;
            let settings_separator = PredefinedMenuItem::separator(app)?;
            #[cfg(target_os = "macos")]
            let mut settings_item_added = false;
            #[cfg(not(target_os = "macos"))]
            let settings_item_added = false;

            #[cfg(target_os = "macos")]
            if let Some(app_menu) = menu
                .items()?
                .first()
                .and_then(|item| item.as_submenu().cloned())
            {
                app_menu
                    .insert_items(&[&settings_item, &check_updates_item, &install_cli_item], 1)?;
                settings_item_added = true;
            }

            let new_file = MenuItem::with_id(app, "file_new", "New", true, Some("CmdOrCtrl+N"))?;
            let open_file =
                MenuItem::with_id(app, "file_open", "Open...", true, Some("CmdOrCtrl+O"))?;
            let recent_empty = MenuItem::with_id(
                app,
                "file_recent_empty",
                "No Recent Documents",
                false,
                None::<&str>,
            )?;
            let open_recent = Submenu::with_id_and_items(
                app,
                RECENT_MENU_ID,
                "Open Recent",
                true,
                &[&recent_empty],
            )?;
            let save_file = MenuItem::with_id(app, "file_save", "Save", true, Some("CmdOrCtrl+S"))?;
            let save_file_as = MenuItem::with_id(
                app,
                "file_save_as",
                "Save As...",
                true,
                Some("CmdOrCtrl+Shift+S"),
            )?;
            let file_open_separator = PredefinedMenuItem::separator(app)?;
            let file_save_separator = PredefinedMenuItem::separator(app)?;
            let close_tab = MenuItem::with_id(
                app,
                "file_close_tab",
                "Close Tab",
                true,
                Some("CmdOrCtrl+W"),
            )?;
            let close_window = MenuItem::with_id(
                app,
                "file_close_window",
                "Close Window",
                true,
                Some("CmdOrCtrl+Shift+W"),
            )?;
            if let Some(file_menu) = menu.items()?.into_iter().find_map(|item| {
                item.as_submenu()
                    .cloned()
                    .filter(|submenu| submenu.text().map(|text| text == "File").unwrap_or(false))
            }) {
                let item_count = file_menu.items()?.len();
                for index in (0..item_count).rev() {
                    file_menu.remove_at(index)?;
                }
                file_menu.append_items(&[
                    &new_file,
                    &open_file,
                    &open_recent,
                    &file_open_separator,
                    &save_file,
                    &save_file_as,
                    &file_save_separator,
                    &close_tab,
                    &close_window,
                ])?;

                if !settings_item_added {
                    file_menu.insert_items(
                        &[
                            &settings_item,
                            &check_updates_item,
                            &install_cli_item,
                            &settings_separator,
                        ],
                        0,
                    )?;
                }
            }

            let find_separator = PredefinedMenuItem::separator(app)?;
            let find = MenuItem::with_id(app, "edit_find", "Find", true, Some("CmdOrCtrl+F"))?;
            let find_and_replace = MenuItem::with_id(
                app,
                "edit_find_and_replace",
                "Find and Replace...",
                true,
                Some("CmdOrCtrl+Alt+F"),
            )?;
            let find_next = MenuItem::with_id(
                app,
                "edit_find_next",
                "Find Next",
                true,
                Some("CmdOrCtrl+G"),
            )?;
            let find_previous = MenuItem::with_id(
                app,
                "edit_find_previous",
                "Find Previous",
                true,
                Some("CmdOrCtrl+Shift+G"),
            )?;
            if let Some(edit_menu) = menu.items()?.into_iter().find_map(|item| {
                item.as_submenu()
                    .cloned()
                    .filter(|submenu| submenu.text().map(|text| text == "Edit").unwrap_or(false))
            }) {
                edit_menu.append_items(&[
                    &find_separator,
                    &find,
                    &find_and_replace,
                    &find_next,
                    &find_previous,
                ])?;
            }

            let insert_comment = MenuItem::with_id(
                app,
                "insert_comment",
                "Comment",
                true,
                Some("CmdOrCtrl+Alt+M"),
            )?;
            let insert_comment_separator = PredefinedMenuItem::separator(app)?;
            let insert_table = MenuItem::with_id(
                app,
                "insert_table",
                "Table",
                true,
                Some("CmdOrCtrl+Shift+T"),
            )?;
            let insert_tasks = MenuItem::with_id(
                app,
                "insert_tasks",
                "Task List",
                true,
                Some("CmdOrCtrl+Shift+X"),
            )?;
            let insert_bullets = MenuItem::with_id(
                app,
                "insert_bullets",
                "Bulleted List",
                true,
                Some("CmdOrCtrl+Shift+8"),
            )?;
            let insert_numbers = MenuItem::with_id(
                app,
                "insert_numbers",
                "Numbered List",
                true,
                Some("CmdOrCtrl+Shift+7"),
            )?;
            let insert_menu = Submenu::with_id_and_items(
                app,
                "insert",
                "Insert",
                true,
                &[
                    &insert_comment,
                    &insert_comment_separator,
                    &insert_table,
                    &insert_tasks,
                    &insert_bullets,
                    &insert_numbers,
                ],
            )?;

            menu.insert(&insert_menu, insert_menu_position())?;

            if let Some(window_menu) = menu.items()?.into_iter().find_map(|item| {
                item.as_submenu()
                    .cloned()
                    .filter(|submenu| submenu.text().map(|text| text == "Window").unwrap_or(false))
            }) {
                let item_count = window_menu.items()?.len();
                for index in (0..item_count).rev() {
                    window_menu.remove_at(index)?;
                }

                let previous_tab = MenuItem::with_id(
                    app,
                    "window_previous_tab",
                    "Show Previous Tab",
                    true,
                    Some("CmdOrCtrl+Shift+["),
                )?;
                let next_tab = MenuItem::with_id(
                    app,
                    "window_next_tab",
                    "Show Next Tab",
                    true,
                    Some("CmdOrCtrl+Shift+]"),
                )?;
                let tab_separator = PredefinedMenuItem::separator(app)?;
                let minimize_window = PredefinedMenuItem::minimize(app, None)?;
                let maximize_window = PredefinedMenuItem::maximize(app, None)?;

                window_menu.append_items(&[
                    &previous_tab,
                    &next_tab,
                    &tab_separator,
                    &minimize_window,
                    &maximize_window,
                ])?;
            }

            app.set_menu(menu)?;

            let app_handle = app.handle().clone();
            let recent_menu_state = app.state::<RecentDocumentsMenuState>();

            *recent_menu_state
                .menu
                .lock()
                .expect("recent documents menu state poisoned") = Some(open_recent.clone());

            match read_recent_documents_file(&app_handle) {
                Ok(entries) if !entries.is_empty() => {
                    if let Err(err) =
                        set_recent_documents_menu_entries(&app_handle, &open_recent, &entries)
                    {
                        eprintln!("Unable to restore recent documents menu: {err}");
                    }
                }
                Err(err) => eprintln!("Unable to read recent documents: {err}"),
                _ => {}
            }

            dispatch_native_open_urls(&app_handle, launch_urls_from_args(env::args().collect()));
        }

        #[cfg(target_os = "ios")]
        {
            let _ = app;
        }

        Ok(())
    });

    #[cfg(not(target_os = "ios"))]
    let builder = builder.on_menu_event(|app, event| {
        let menu_id = event.id();
        if menu_id.as_ref() == "app_settings" {
            let _ = app.emit("margin://open-settings", ());
        } else if menu_id.as_ref() == "app_check_updates" {
            let _ = app.emit("margin://check-for-updates", ());
        } else if menu_id.as_ref() == "app_install_cli" {
            show_cli_install_result(install_margin_cli());
        } else if menu_id.as_ref() == "file_new" {
            let _ = app.emit("margin://new-document", ());
        } else if menu_id.as_ref() == "file_open" {
            let _ = app.emit("margin://open-document", ());
        } else if let Some(index) = recent_document_menu_index(menu_id.as_ref()) {
            let _ = app.emit("margin://open-recent-document", index);
        } else if menu_id.as_ref().starts_with(CLEAR_RECENT_MENU_ITEM_PREFIX) {
            let _ = app.emit("margin://clear-recent-documents", ());
        } else if menu_id.as_ref() == "file_save" {
            let _ = app.emit("margin://save-document", ());
        } else if menu_id.as_ref() == "file_save_as" {
            let _ = app.emit("margin://save-document-as", ());
        } else if menu_id.as_ref() == "file_close_tab" {
            let _ = app.emit("margin://close-tab", ());
        } else if menu_id.as_ref() == "file_close_window" {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.close();
            }
        } else if menu_id.as_ref() == "window_previous_tab" {
            let _ = app.emit("margin://previous-tab", ());
        } else if menu_id.as_ref() == "window_next_tab" {
            let _ = app.emit("margin://next-tab", ());
        } else if menu_id.as_ref() == "edit_find" {
            let _ = app.emit("margin://open-find", ());
        } else if menu_id.as_ref() == "edit_find_and_replace" {
            let _ = app.emit("margin://open-find-and-replace", ());
        } else if menu_id.as_ref() == "edit_find_next" {
            let _ = app.emit("margin://find-next", ());
        } else if menu_id.as_ref() == "edit_find_previous" {
            let _ = app.emit("margin://find-previous", ());
        } else if matches!(menu_id.as_ref(), "insert_comment" | "context_add_comment") {
            let _ = app.emit("margin://add-comment", ());
        } else if let Some(kind) = insert_payload(menu_id.as_ref()) {
            let _ = app.emit("margin://insert-block", kind);
        }
    });

    builder
        .invoke_handler(tauri::generate_handler![
            take_pending_open_urls,
            choose_markdown_document,
            open_markdown_document,
            watch_markdown_document,
            choose_markdown_save_path,
            show_comment_context_menu,
            confirm_close_tab,
            quit_app,
            save_markdown_document,
            read_settings,
            write_settings,
            check_for_app_update,
            install_app_update,
            read_recent_documents,
            write_recent_documents
        ])
        .build(tauri::generate_context!())
        .expect("failed to build Margin desktop app")
        .run(|app_handle, event| match event {
            #[cfg(any(target_os = "macos", target_os = "ios"))]
            tauri::RunEvent::Opened { urls } => {
                dispatch_native_open_urls(
                    app_handle,
                    urls.into_iter().map(|url| url.to_string()).collect(),
                );
            }
            _ => {
                #[cfg(not(any(target_os = "macos", target_os = "ios")))]
                let _ = app_handle;
            }
        });
}

#[cfg(test)]
mod settings_tests {
    use super::*;

    #[test]
    fn parses_local_user_name_from_settings() {
        let settings =
            parse_settings_toml("theme = \"dark\"\nlocal_user_name = \"Ada Lovelace\"\n");

        assert_eq!(settings.theme, "dark");
        assert_eq!(settings.local_user_name, "Ada Lovelace");
    }

    #[test]
    fn round_trips_quoted_local_user_name() {
        let settings = AppSettings {
            theme: "light".to_string(),
            local_user_name: "Ada # One".to_string(),
        };

        let parsed = parse_settings_toml(&settings_toml(&settings));

        assert_eq!(parsed.theme, "light");
        assert_eq!(parsed.local_user_name, "Ada # One");
    }
}
