use ignore::{
    gitignore::{Gitignore, GitignoreBuilder},
    Match,
};
#[cfg(not(target_os = "ios"))]
use notify::{Config, Event, EventKind, RecommendedWatcher, RecursiveMode, Watcher};
use serde::{Deserialize, Serialize};
use std::env;
use std::{
    collections::{HashMap, HashSet},
    fs,
    path::{Path, PathBuf},
    sync::{
        atomic::{AtomicBool, Ordering},
        Arc, Mutex,
    },
    time::{SystemTime, UNIX_EPOCH},
};
#[cfg(not(target_os = "ios"))]
use std::{
    io::{Read, Write},
    net::{TcpListener, TcpStream},
    process::Command,
    thread,
    time::{Duration, Instant},
};
#[cfg(not(target_os = "ios"))]
use tauri::menu::{Menu, MenuItem, PredefinedMenuItem, Submenu};
use tauri::{AppHandle, Emitter, Manager, State, Wry};
#[cfg(not(target_os = "ios"))]
use tauri::{Runtime, Url};
#[cfg(not(target_os = "ios"))]
use tauri_plugin_updater::{Updater, UpdaterExt};

#[cfg(not(target_os = "ios"))]
const RECENT_MENU_ID: &str = "file_open_recent";
#[cfg(not(target_os = "ios"))]
const RECENT_MENU_ITEM_PREFIX: &str = "file_recent_";
#[cfg(not(target_os = "ios"))]
const CLEAR_RECENT_MENU_ITEM_PREFIX: &str = "file_clear_recent_";
const RECENT_DOCUMENT_LIMIT: usize = 10;
const RECENT_DOCUMENTS_FILE_NAME: &str = "recent-documents.json";
const SETTINGS_FILE_NAME: &str = "settings.toml";
const DEFAULT_THEME: &str = "auto";
const DEFAULT_LOCAL_USER_NAME: &str = "Me";
const DIRECTORY_TREE_MAX_DEPTH: usize = 12;
const DIRECTORY_TREE_MAX_ENTRIES: usize = 5_000;
#[cfg(not(target_os = "ios"))]
const UPDATER_ENDPOINT: &str =
    "https://github.com/soseinai/margin/releases/latest/download/latest.json";
#[cfg(not(target_os = "ios"))]
const UPDATER_PUBLIC_KEY: &str = "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDk3NTk2MUZGN0I5NzA0QzkKUldUSkJKZDcvMkZabHcrNXlvcEJFeFUxOHZ3TTI0ZnBsbDQxUzJ0cDFNNEs0SHV5QzVZMHpBTzYK";
#[cfg(not(target_os = "ios"))]
const SOSEIN_OAUTH_TIMEOUT: Duration = Duration::from_secs(5 * 60);
#[cfg(target_os = "macos")]
const CLI_MARKER: &str = "# Generated by Margin. Safe to overwrite.";
#[cfg(target_os = "macos")]
const CLI_NAME: &str = "margin";

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct NativeMarkdownDocument {
    path: String,
    name: String,
    markdown: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct NativeOpenPathPayload {
    kind: NativeOpenPathKind,
    document: Option<NativeMarkdownDocument>,
    directory: Option<NativeDirectoryTree>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
enum NativeOpenPathKind {
    Document,
    Directory,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct NativeDirectoryTree {
    path: String,
    name: String,
    entries: Vec<NativeDirectoryEntry>,
}

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct NativeDirectoryEntry {
    path: String,
    name: String,
    kind: NativeDirectoryEntryKind,
    children: Vec<NativeDirectoryEntry>,
}

#[derive(Serialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
enum NativeDirectoryEntryKind {
    Directory,
    Markdown,
    File,
}

#[derive(Clone, Default)]
struct DirectoryIgnoreRules {
    matchers: Vec<Arc<Gitignore>>,
}

impl DirectoryIgnoreRules {
    fn for_directory(path: &Path) -> Self {
        Self::default().with_directory(path)
    }

    fn with_directory(&self, path: &Path) -> Self {
        let gitignore_path = path.join(".gitignore");

        if !gitignore_path.is_file() {
            return self.clone();
        }

        let mut builder = GitignoreBuilder::new(path);

        if let Some(err) = builder.add(&gitignore_path) {
            eprintln!("Unable to parse {}: {err}", gitignore_path.display());
            return self.clone();
        }

        match builder.build() {
            Ok(gitignore) => {
                let mut matchers = self.matchers.clone();
                matchers.push(Arc::new(gitignore));

                Self { matchers }
            }
            Err(err) => {
                eprintln!("Unable to build ignore rules for {}: {err}", path.display());
                self.clone()
            }
        }
    }

    fn is_ignored(&self, path: &Path, is_directory: bool) -> bool {
        let mut ignored = false;

        for matcher in &self.matchers {
            match matcher.matched(path, is_directory) {
                Match::Ignore(_) => ignored = true,
                Match::Whitelist(_) => ignored = false,
                Match::None => {}
            }
        }

        ignored
    }
}

#[cfg(not(target_os = "ios"))]
#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct NativeMarkdownDocumentChange {
    path: String,
}

#[derive(Deserialize, Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct RecentDocumentEntry {
    title: String,
    path: String,
    #[serde(default)]
    opened_at: u64,
}

#[derive(Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
struct AppSettings {
    #[serde(default = "default_theme")]
    theme: String,
    #[serde(default = "default_local_user_name")]
    local_user_name: String,
    #[serde(default)]
    sosein_cloud_enabled: bool,
}

#[derive(Serialize, Deserialize)]
struct SoseinOAuthUser {
    id: String,
    email: String,
}

#[derive(Serialize, Deserialize)]
struct SoseinOAuthWorkspace {
    id: String,
    name: String,
}

#[derive(Serialize, Deserialize)]
struct SoseinOAuthSession {
    session_token: String,
    user: SoseinOAuthUser,
    default_workspace: SoseinOAuthWorkspace,
    expires_at: String,
}

#[cfg(not(target_os = "ios"))]
#[derive(Serialize)]
struct SoseinOAuthHandoffExchangeRequest<'a> {
    handoff_code: &'a str,
}

#[cfg(not(target_os = "ios"))]
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct NativeSoseinApiResponse {
    status: u16,
    body: Option<serde_json::Value>,
    body_text: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct AppUpdateMetadata {
    current_version: String,
    version: String,
    notes: Option<String>,
}

impl Default for AppSettings {
    fn default() -> Self {
        Self {
            theme: DEFAULT_THEME.to_string(),
            local_user_name: default_local_user_name(),
            sosein_cloud_enabled: false,
        }
    }
}

#[derive(Default)]
struct NativeOpenState {
    frontend_ready: AtomicBool,
    pending_urls: Mutex<Vec<String>>,
}

#[cfg(not(target_os = "ios"))]
#[derive(Default)]
struct WatchedDocumentState {
    watchers: Mutex<HashMap<String, RecommendedWatcher>>,
}

#[cfg(not(target_os = "ios"))]
#[derive(Default)]
struct RecentDocumentsMenuState {
    menu: Mutex<Option<Submenu<Wry>>>,
}

#[tauri::command]
fn take_pending_open_urls(state: State<NativeOpenState>) -> Vec<String> {
    state.frontend_ready.store(true, Ordering::SeqCst);

    let mut pending_urls = state
        .pending_urls
        .lock()
        .expect("pending open URL state poisoned");
    std::mem::take(&mut *pending_urls)
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn choose_markdown_document() -> Result<Option<NativeMarkdownDocument>, String> {
    let picked = rfd::FileDialog::new()
        .add_filter("Markdown Documents", &["md", "markdown", "txt"])
        .pick_file();

    picked
        .map(|path| read_markdown_document_from_path(&path))
        .transpose()
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn choose_markdown_document() -> Result<Option<NativeMarkdownDocument>, String> {
    Err(ios_file_picker_message())
}

#[tauri::command]
fn open_markdown_document(path: String) -> Result<NativeMarkdownDocument, String> {
    read_markdown_document_from_path(&PathBuf::from(path))
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn choose_directory() -> Result<Option<NativeDirectoryTree>, String> {
    rfd::FileDialog::new()
        .pick_folder()
        .map(|path| read_directory_tree_from_path(&path))
        .transpose()
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn choose_directory() -> Result<Option<NativeDirectoryTree>, String> {
    Err(ios_file_picker_message())
}

#[tauri::command]
fn read_directory_tree(path: String) -> Result<NativeDirectoryTree, String> {
    read_directory_tree_from_path(&PathBuf::from(path))
}

#[tauri::command]
fn open_native_path(path: String) -> Result<NativeOpenPathPayload, String> {
    let path = PathBuf::from(path);

    if path.is_dir() {
        return read_directory_tree_from_path(&path).map(|directory| NativeOpenPathPayload {
            kind: NativeOpenPathKind::Directory,
            document: None,
            directory: Some(directory),
        });
    }

    read_markdown_document_from_path(&path).map(|document| NativeOpenPathPayload {
        kind: NativeOpenPathKind::Document,
        document: Some(document),
        directory: None,
    })
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn watch_markdown_document(
    app: AppHandle,
    state: State<WatchedDocumentState>,
    path: String,
) -> Result<(), String> {
    let path = PathBuf::from(path)
        .canonicalize()
        .map_err(|err| format!("Unable to watch document: {err}"))?;

    ensure_markdown_path(&path)?;

    let parent = path
        .parent()
        .ok_or_else(|| "Unable to watch document without a parent directory".to_string())?
        .to_path_buf();
    let key = path.to_string_lossy().to_string();
    let mut watchers = state
        .watchers
        .lock()
        .expect("watched document state poisoned");

    if watchers.contains_key(&key) {
        return Ok(());
    }

    let watched_path = path.clone();
    let watched_path_string = key.clone();
    let app_handle = app.clone();
    let mut watcher = RecommendedWatcher::new(
        move |result: notify::Result<Event>| match result {
            Ok(event) => {
                if should_emit_document_change(&event, &watched_path) {
                    let _ = app_handle.emit(
                        "margin://document-changed",
                        NativeMarkdownDocumentChange {
                            path: watched_path_string.clone(),
                        },
                    );
                }
            }
            Err(err) => eprintln!("Unable to watch Markdown document: {err}"),
        },
        Config::default(),
    )
    .map_err(|err| format!("Unable to watch {}: {err}", display_name(&path)))?;

    watcher
        .watch(&parent, RecursiveMode::NonRecursive)
        .map_err(|err| format!("Unable to watch {}: {err}", display_name(&path)))?;
    watchers.insert(key, watcher);

    Ok(())
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn watch_markdown_document(_path: String) -> Result<(), String> {
    Ok(())
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn choose_markdown_save_path(suggested_name: String) -> Result<Option<String>, String> {
    let suggested_name = if suggested_name.trim().is_empty() {
        "document.md"
    } else {
        suggested_name.trim()
    };

    Ok(rfd::FileDialog::new()
        .add_filter("Markdown Documents", &["md", "markdown", "txt"])
        .set_file_name(suggested_name)
        .save_file()
        .map(normalized_save_path)
        .map(|path| path.to_string_lossy().to_string()))
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn choose_markdown_save_path(_suggested_name: String) -> Result<Option<String>, String> {
    Err(ios_file_picker_message())
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn show_comment_context_menu(window: tauri::WebviewWindow, x: f64, y: f64) -> Result<(), String> {
    let add_comment = MenuItem::with_id(
        window.app_handle(),
        "context_add_comment",
        "Add Comment",
        true,
        Some("CmdOrCtrl+Alt+M"),
    )
    .map_err(|err| err.to_string())?;
    let menu =
        Menu::with_items(window.app_handle(), &[&add_comment]).map_err(|err| err.to_string())?;

    window
        .popup_menu_at(&menu, tauri::LogicalPosition::new(x, y))
        .map_err(|err| err.to_string())
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn show_comment_context_menu(_x: f64, _y: f64) -> Result<(), String> {
    Ok(())
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn confirm_close_tab(title: String) -> bool {
    let title = if title.trim().is_empty() {
        "this tab"
    } else {
        title.trim()
    };

    matches!(
        rfd::MessageDialog::new()
            .set_level(rfd::MessageLevel::Warning)
            .set_title("Close Tab?")
            .set_description(format!(
                "{title} has unsaved changes. If you close it now, those changes will be discarded."
            ))
            .set_buttons(rfd::MessageButtons::OkCancelCustom(
                "Discard and Close".to_string(),
                "Cancel".to_string(),
            ))
            .show(),
        rfd::MessageDialogResult::Custom(value) if value == "Discard and Close"
    )
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn confirm_close_tab(_title: String) -> bool {
    false
}

#[tauri::command]
fn quit_app(app: AppHandle) {
    app.exit(0);
}

#[tauri::command]
fn print_window(window: tauri::WebviewWindow) -> Result<(), String> {
    #[cfg(not(target_os = "ios"))]
    {
        window
            .print()
            .map_err(|err| format!("Unable to print document: {err}"))
    }

    #[cfg(target_os = "ios")]
    {
        let _ = window;
        Err("Printing is not available on iOS.".to_string())
    }
}

#[tauri::command]
fn save_markdown_document(
    path: String,
    markdown: String,
) -> Result<NativeMarkdownDocument, String> {
    let path = normalized_save_path(PathBuf::from(path));
    ensure_markdown_path(&path)?;
    fs::write(&path, &markdown)
        .map_err(|err| format!("Unable to save {}: {err}", display_name(&path)))?;

    Ok(markdown_document_payload(&path, markdown))
}

#[tauri::command]
fn read_settings(app: AppHandle) -> Result<AppSettings, String> {
    read_settings_file(&app)
}

#[tauri::command]
fn write_settings(app: AppHandle, settings: AppSettings) -> Result<AppSettings, String> {
    let current_settings = read_settings_file(&app).unwrap_or_default();
    let settings = AppSettings {
        theme: normalized_theme(&settings.theme).to_string(),
        local_user_name: normalized_local_user_name(&settings.local_user_name),
        sosein_cloud_enabled: current_settings.sosein_cloud_enabled,
    };
    let path = settings_path(&app)?;

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("Unable to create settings directory: {err}"))?;
    }

    fs::write(&path, settings_toml(&settings))
        .map_err(|err| format!("Unable to write {}: {err}", display_name(&path)))?;

    Ok(settings)
}

#[tauri::command]
fn sosein_cloud_enabled(app: AppHandle) -> bool {
    read_settings_file(&app)
        .map(|settings| settings.sosein_cloud_enabled)
        .unwrap_or(false)
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
async fn start_sosein_oauth_login(server_url: String) -> Result<SoseinOAuthSession, String> {
    tauri::async_runtime::spawn_blocking(move || run_sosein_oauth_loopback(server_url))
        .await
        .map_err(|err| format!("Unable to run Sosein Cloud login: {err}"))?
}

#[cfg(target_os = "ios")]
#[tauri::command]
async fn start_sosein_oauth_login(_server_url: String) -> Result<SoseinOAuthSession, String> {
    Err("Sosein Cloud OAuth login is not available on iOS.".to_string())
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
async fn sosein_api_request(
    server_url: String,
    method: String,
    path: String,
    session_token: Option<String>,
    body: Option<serde_json::Value>,
) -> Result<NativeSoseinApiResponse, String> {
    tauri::async_runtime::spawn_blocking(move || {
        run_sosein_api_request(server_url, method, path, session_token, body)
    })
    .await
    .map_err(|err| format!("Unable to run Sosein Cloud request: {err}"))?
}

#[cfg(target_os = "ios")]
#[tauri::command]
async fn sosein_api_request(
    _server_url: String,
    _method: String,
    _path: String,
    _session_token: Option<String>,
    _body: Option<serde_json::Value>,
) -> Result<serde_json::Value, String> {
    Err("Sosein Cloud API requests are not available on iOS.".to_string())
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
async fn check_for_app_update(app: AppHandle) -> Result<Option<AppUpdateMetadata>, String> {
    let updater = app_updater(&app).map_err(|err| format!("Unable to check for updates: {err}"))?;
    let update = updater
        .check()
        .await
        .map_err(|err| format!("Unable to check for updates: {err}"))?;

    Ok(update.map(|update| AppUpdateMetadata {
        current_version: update.current_version,
        version: update.version,
        notes: update.body,
    }))
}

#[cfg(target_os = "ios")]
#[tauri::command]
async fn check_for_app_update() -> Result<Option<AppUpdateMetadata>, String> {
    Ok(None)
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
async fn install_app_update(app: AppHandle) -> Result<(), String> {
    #[cfg(target_os = "macos")]
    ensure_macos_app_update_location()?;

    let updater = app_updater(&app).map_err(|err| format!("Unable to install update: {err}"))?;
    let Some(update) = updater
        .check()
        .await
        .map_err(|err| format!("Unable to install update: {err}"))?
    else {
        return Err("No update is available.".to_string());
    };

    update
        .download_and_install(|_, _| {}, || {})
        .await
        .map_err(|err| format!("Unable to install update: {err}"))?;
    app.restart();
}

#[cfg(target_os = "ios")]
#[tauri::command]
async fn install_app_update() -> Result<(), String> {
    Err("App updates are not available on iOS.".to_string())
}

#[tauri::command]
fn read_recent_documents(app: AppHandle) -> Result<Vec<RecentDocumentEntry>, String> {
    read_recent_documents_file(&app)
}

#[cfg(not(target_os = "ios"))]
#[tauri::command]
fn write_recent_documents(
    app: AppHandle,
    menu_state: State<RecentDocumentsMenuState>,
    entries: Vec<RecentDocumentEntry>,
) -> Result<Vec<RecentDocumentEntry>, String> {
    let entries = normalized_recent_documents(entries);

    write_recent_documents_file(&app, &entries)?;
    update_recent_documents_menu(&app, &menu_state, &entries)?;

    Ok(entries)
}

#[cfg(target_os = "ios")]
#[tauri::command]
fn write_recent_documents(
    app: AppHandle,
    entries: Vec<RecentDocumentEntry>,
) -> Result<Vec<RecentDocumentEntry>, String> {
    let entries = normalized_recent_documents(entries);

    write_recent_documents_file(&app, &entries)?;

    Ok(entries)
}

#[cfg(not(target_os = "ios"))]
fn set_recent_documents_menu_entries(
    app: &AppHandle,
    recent_menu: &Submenu<Wry>,
    entries: &[RecentDocumentEntry],
) -> Result<(), String> {
    clear_submenu(recent_menu)?;

    let nonce = recent_menu_nonce();

    if entries.is_empty() {
        let empty = MenuItem::with_id(
            app,
            format!("file_recent_empty_{nonce}"),
            "No Recent Documents",
            false,
            None::<&str>,
        )
        .map_err(|err| err.to_string())?;
        recent_menu.append(&empty).map_err(|err| err.to_string())?;
        return Ok(());
    }

    for (index, entry) in entries.iter().take(RECENT_DOCUMENT_LIMIT).enumerate() {
        let item = MenuItem::with_id(
            app,
            format!("{RECENT_MENU_ITEM_PREFIX}{nonce}_{index}"),
            recent_menu_label(&entry.title),
            true,
            None::<&str>,
        )
        .map_err(|err| err.to_string())?;
        recent_menu.append(&item).map_err(|err| err.to_string())?;
    }

    let separator = PredefinedMenuItem::separator(app).map_err(|err| err.to_string())?;
    let clear = MenuItem::with_id(
        app,
        format!("{CLEAR_RECENT_MENU_ITEM_PREFIX}{nonce}"),
        "Clear Menu",
        true,
        None::<&str>,
    )
    .map_err(|err| err.to_string())?;
    recent_menu
        .append_items(&[&separator, &clear])
        .map_err(|err| err.to_string())?;

    Ok(())
}

#[cfg(not(target_os = "ios"))]
fn update_recent_documents_menu(
    app: &AppHandle,
    menu_state: &State<RecentDocumentsMenuState>,
    entries: &[RecentDocumentEntry],
) -> Result<(), String> {
    let recent_menu = menu_state
        .menu
        .lock()
        .expect("recent documents menu state poisoned")
        .clone()
        .ok_or_else(|| "Recent documents menu is not available".to_string())?;

    set_recent_documents_menu_entries(app, &recent_menu, entries)
}

#[cfg(not(target_os = "ios"))]
fn app_updater(app: &AppHandle) -> Result<Updater, tauri_plugin_updater::Error> {
    app.updater_builder()
        .pubkey(UPDATER_PUBLIC_KEY)
        .endpoints(vec![UPDATER_ENDPOINT.parse()?])?
        .build()
}

#[cfg(target_os = "macos")]
fn ensure_macos_app_update_location() -> Result<(), String> {
    const NO_SUCH_FILE_ERROR: i32 = 2;
    const READ_ONLY_FILESYSTEM_ERROR: i32 = 30;

    let Some(app_bundle_path) = current_macos_app_bundle_path()? else {
        return Ok(());
    };
    if is_transient_macos_app_location(&app_bundle_path) {
        return Err(macos_update_location_error(&app_bundle_path));
    }

    let Some(parent) = app_bundle_path.parent() else {
        return Ok(());
    };

    let probe_path = parent.join(format!(".margin-update-write-test-{}", std::process::id()));

    match fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&probe_path)
    {
        Ok(_) => {
            let _ = fs::remove_file(&probe_path);
            Ok(())
        }
        Err(err)
            if matches!(
                err.raw_os_error(),
                Some(NO_SUCH_FILE_ERROR | READ_ONLY_FILESYSTEM_ERROR)
            ) =>
        {
            Err(macos_update_location_error(&app_bundle_path))
        }
        Err(_) => Ok(()),
    }
}

#[cfg(target_os = "macos")]
fn current_macos_app_bundle_path() -> Result<Option<PathBuf>, String> {
    let executable_path =
        env::current_exe().map_err(|err| format!("Unable to locate the running app: {err}"))?;

    Ok(macos_app_bundle_path_from_executable(&executable_path))
}

#[cfg(target_os = "macos")]
fn macos_app_bundle_path_from_executable(executable_path: &Path) -> Option<PathBuf> {
    executable_path
        .ancestors()
        .find(|path| path.extension().and_then(|extension| extension.to_str()) == Some("app"))
        .map(PathBuf::from)
}

#[cfg(target_os = "macos")]
fn is_transient_macos_app_location(app_bundle_path: &Path) -> bool {
    app_bundle_path.starts_with("/Volumes")
}

#[cfg(target_os = "macos")]
fn macos_update_location_error(app_bundle_path: &Path) -> String {
    format!(
        "Margin is running from a location that cannot be updated in place: {}. Drag Margin to Applications, quit this copy, reopen /Applications/Margin.app, then install the update.",
        app_bundle_path.display()
    )
}

#[cfg(not(target_os = "ios"))]
fn show_cli_install_result(result: Result<PathBuf, String>) {
    match result {
        Ok(path) => {
            let _ = rfd::MessageDialog::new()
                .set_level(rfd::MessageLevel::Info)
                .set_title("Command Installed")
                .set_description(format!(
                    "Installed the margin command at {}.\n\nNote: make sure ~/.local/bin is in your PATH",
                    path.display()
                ))
                .set_buttons(rfd::MessageButtons::Ok)
                .show();
        }
        Err(err) => {
            let _ = rfd::MessageDialog::new()
                .set_level(rfd::MessageLevel::Error)
                .set_title("Unable to Install Command")
                .set_description(err)
                .set_buttons(rfd::MessageButtons::Ok)
                .show();
        }
    }
}

#[cfg(target_os = "macos")]
fn install_margin_cli() -> Result<PathBuf, String> {
    let app_bundle_path = current_macos_app_bundle_path()?;

    if let Some(app_bundle_path) = &app_bundle_path {
        if is_transient_macos_app_location(app_bundle_path) {
            return Err(format!(
                "Margin is running from {}. Drag Margin to Applications, quit this copy, reopen /Applications/Margin.app, then install the command again.",
                app_bundle_path.display()
            ));
        }
    }

    let destination = margin_cli_destination()?;
    let script = margin_cli_script(app_bundle_path.as_deref());

    write_executable_file(&destination, &script)?;

    Ok(destination)
}

#[cfg(all(not(target_os = "macos"), not(target_os = "ios")))]
fn install_margin_cli() -> Result<PathBuf, String> {
    Err("The margin command installer is currently only available on macOS.".to_string())
}

#[cfg(target_os = "macos")]
fn margin_cli_destination() -> Result<PathBuf, String> {
    let destination = margin_cli_destination_candidate()?;

    if destination.exists() {
        if existing_margin_cli(&destination)? {
            ensure_writable_destination(&destination)?;
            return Ok(destination);
        }

        return Err(format!(
            "A different command already exists at {}. Move or rename that command before installing Margin's CLI.",
            destination.display()
        ));
    }

    ensure_writable_destination(&destination)?;

    Ok(destination)
}

#[cfg(target_os = "macos")]
fn margin_cli_destination_candidate() -> Result<PathBuf, String> {
    env::var_os("HOME")
        .map(|home| {
            PathBuf::from(home)
                .join(".local")
                .join("bin")
                .join(CLI_NAME)
        })
        .ok_or_else(|| {
            "Margin could not locate your home directory to install ~/.local/bin/margin."
                .to_string()
        })
}

#[cfg(target_os = "macos")]
fn existing_margin_cli(path: &Path) -> Result<bool, String> {
    if !path.is_file() {
        return Ok(false);
    }

    let contents = fs::read(path).map_err(|err| {
        format!(
            "Unable to inspect existing command at {}: {err}",
            path.display()
        )
    })?;

    Ok(contents
        .windows(CLI_MARKER.len())
        .any(|window| window == CLI_MARKER.as_bytes()))
}

#[cfg(target_os = "macos")]
fn ensure_writable_destination(path: &Path) -> Result<(), String> {
    let parent = path.parent().ok_or_else(|| {
        format!(
            "Unable to locate the parent directory for {}",
            path.display()
        )
    })?;

    fs::create_dir_all(parent)
        .map_err(|err| format!("Unable to create {}: {err}", parent.display()))?;

    let probe_path = parent.join(format!(".margin-cli-install-probe-{}", std::process::id()));

    match fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&probe_path)
    {
        Ok(_) => {
            let _ = fs::remove_file(&probe_path);
            Ok(())
        }
        Err(err) => Err(format!("Unable to write to {}: {err}", parent.display())),
    }
}

#[cfg(target_os = "macos")]
fn write_executable_file(path: &Path, contents: &str) -> Result<(), String> {
    use std::os::unix::fs::PermissionsExt;

    let parent = path.parent().ok_or_else(|| {
        format!(
            "Unable to locate the parent directory for {}",
            path.display()
        )
    })?;
    let temporary_path = parent.join(format!(".margin-cli-install-{}", std::process::id()));

    fs::write(&temporary_path, contents)
        .map_err(|err| format!("Unable to write {}: {err}", temporary_path.display()))?;
    fs::set_permissions(&temporary_path, fs::Permissions::from_mode(0o755)).map_err(|err| {
        format!(
            "Unable to make {} executable: {err}",
            temporary_path.display()
        )
    })?;
    if let Err(err) = fs::rename(&temporary_path, path) {
        let _ = fs::remove_file(&temporary_path);

        return Err(format!("Unable to install {}: {err}", path.display()));
    }

    Ok(())
}

#[cfg(target_os = "macos")]
fn margin_cli_script(app_bundle_path: Option<&Path>) -> String {
    let app_bundle = app_bundle_path
        .map(shell_single_quoted)
        .unwrap_or_else(|| "''".to_string());

    format!(
        r#"#!/bin/zsh
{CLI_MARKER}
set -e

app_bundle={app_bundle}

args=()
for arg in "$@"; do
  case "$arg" in
    margin://*|file://*|/*)
      args+=("$arg")
      ;;
    *)
      args+=("$PWD/$arg")
      ;;
  esac
done

if [[ -n "$app_bundle" && -d "$app_bundle" ]]; then
  exec open -n "$app_bundle" --args "${{args[@]}}"
fi

exec open -n -a "Margin" --args "${{args[@]}}"
"#
    )
}

#[cfg(target_os = "macos")]
fn shell_single_quoted(value: &Path) -> String {
    let value = value.to_string_lossy();
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(all(test, target_os = "macos"))]
mod tests {
    use super::*;

    #[test]
    fn finds_macos_app_bundle_from_executable_path() {
        let executable_path = Path::new("/Applications/Margin.app/Contents/MacOS/margin-desktop");

        assert_eq!(
            macos_app_bundle_path_from_executable(executable_path),
            Some(PathBuf::from("/Applications/Margin.app"))
        );
    }

    #[test]
    fn ignores_executable_paths_outside_app_bundles() {
        let executable_path = Path::new("/usr/local/bin/margin-desktop");

        assert_eq!(macos_app_bundle_path_from_executable(executable_path), None);
    }

    #[test]
    fn treats_apps_launched_from_mounted_volumes_as_transient() {
        assert!(is_transient_macos_app_location(Path::new(
            "/Volumes/Margin/Margin.app"
        )));
        assert!(!is_transient_macos_app_location(Path::new(
            "/Applications/Margin.app"
        )));
    }

    #[test]
    fn update_location_error_points_user_to_applications_copy() {
        let message = macos_update_location_error(Path::new("/Volumes/Margin/Margin.app"));

        assert!(message.contains("/Volumes/Margin/Margin.app"));
        assert!(message.contains("/Applications/Margin.app"));
    }

    #[test]
    fn cli_script_opens_current_app_bundle_with_arguments() {
        let script = margin_cli_script(Some(Path::new("/Applications/Margin.app")));

        assert!(script.contains(CLI_MARKER));
        assert!(script.contains("app_bundle='/Applications/Margin.app'"));
        assert!(script.contains("exec open -n \"$app_bundle\" --args \"${args[@]}\""));
        assert!(script.contains("args+=(\"$PWD/$arg\")"));
    }

    #[test]
    fn launch_url_from_arg_accepts_directories() {
        let directory =
            env::temp_dir().join(format!("margin-open-folder-test-{}", std::process::id()));
        fs::create_dir_all(&directory).expect("test directory can be created");

        let url = launch_url_from_arg(directory.to_string_lossy().to_string());

        fs::remove_dir_all(&directory).expect("test directory can be removed");
        assert!(url
            .as_deref()
            .is_some_and(|value| value.starts_with("file://")));
    }

    #[test]
    fn shell_quotes_app_bundle_paths() {
        assert_eq!(
            shell_single_quoted(Path::new("/Applications/Margin's App.app")),
            "'/Applications/Margin'\\''s App.app'"
        );
    }
}

#[cfg(test)]
mod native_document_tests {
    use super::*;

    fn temp_test_dir(name: &str) -> PathBuf {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("system time is before unix epoch")
            .as_nanos();
        let dir = std::env::temp_dir().join(format!(
            "margin-desktop-{name}-{}-{nanos}",
            std::process::id()
        ));

        fs::create_dir_all(&dir).expect("failed to create temp test directory");

        dir
    }

    #[test]
    fn save_markdown_document_adds_extension_and_round_trips() {
        let dir = temp_test_dir("save-open");
        let requested_path = dir.join("Brief");

        let saved = save_markdown_document(
            requested_path.to_string_lossy().to_string(),
            "# Brief\n\nSaved from Rust.".to_string(),
        )
        .expect("document should save");

        assert_eq!(saved.name, "Brief.md");
        assert_eq!(
            Path::new(&saved.path)
                .extension()
                .and_then(|extension| extension.to_str()),
            Some("md")
        );
        assert_eq!(
            fs::read_to_string(&saved.path).expect("saved markdown should exist"),
            "# Brief\n\nSaved from Rust."
        );

        let opened = open_markdown_document(saved.path.clone()).expect("document should open");
        assert_eq!(opened.name, "Brief.md");
        assert_eq!(opened.path, saved.path);
        assert_eq!(opened.markdown, "# Brief\n\nSaved from Rust.");

        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn rejects_non_markdown_paths_for_open_and_save() {
        let dir = temp_test_dir("reject-extension");
        let pdf_path = dir.join("Brief.pdf");
        fs::write(&pdf_path, "not markdown").expect("failed to write test file");

        assert!(
            save_markdown_document(pdf_path.to_string_lossy().to_string(), "body".to_string())
                .is_err()
        );
        assert!(open_markdown_document(pdf_path.to_string_lossy().to_string()).is_err());

        assert!(is_markdown_path(Path::new("Draft.MD")));
        assert!(is_markdown_path(Path::new("Draft.markdown")));
        assert!(is_markdown_path(Path::new("Draft.txt")));
        assert!(!is_markdown_path(Path::new("Draft.pdf")));
        assert!(!is_markdown_path(Path::new("Draft")));

        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn markdown_payload_uses_canonical_path_and_file_name() {
        let dir = temp_test_dir("payload");
        let path = dir.join("Nested.md");
        fs::write(&path, "Body").expect("failed to write test file");

        let payload = markdown_document_payload(&path, "Body".to_string());

        assert_eq!(payload.name, "Nested.md");
        assert_eq!(
            payload.path,
            path.canonicalize()
                .expect("test file should canonicalize")
                .to_string_lossy()
                .to_string()
        );
        assert_eq!(payload.markdown, "Body");

        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn normalizes_recent_documents_by_path_title_and_limit() {
        let entries = vec![
            RecentDocumentEntry {
                title: "   ".to_string(),
                path: "  /tmp/One.md  ".to_string(),
                opened_at: 9,
            },
            RecentDocumentEntry {
                title: "Duplicate".to_string(),
                path: "/tmp/One.md".to_string(),
                opened_at: 8,
            },
            RecentDocumentEntry {
                title: "Missing path".to_string(),
                path: "   ".to_string(),
                opened_at: 7,
            },
            RecentDocumentEntry {
                title: "Two".to_string(),
                path: "/tmp/Two.md".to_string(),
                opened_at: 6,
            },
        ]
        .into_iter()
        .chain((0..12).map(|index| RecentDocumentEntry {
            title: format!("Extra {index}"),
            path: format!("/tmp/Extra-{index}.md"),
            opened_at: index,
        }))
        .collect();

        let normalized = normalized_recent_documents(entries);

        assert_eq!(normalized.len(), RECENT_DOCUMENT_LIMIT);
        assert_eq!(normalized[0].title, "One.md");
        assert_eq!(normalized[0].path, "/tmp/One.md");
        assert_eq!(normalized[0].opened_at, 9);
        assert_eq!(normalized[1].title, "Two");
        assert_eq!(normalized[1].path, "/tmp/Two.md");
        assert!(!normalized.iter().any(|entry| entry.path.trim().is_empty()));
        assert_eq!(
            normalized
                .iter()
                .filter(|entry| entry.path == "/tmp/One.md")
                .count(),
            1
        );
    }

    #[test]
    fn normalizes_settings_values_for_parse_and_serialize() {
        let settings = parse_settings_toml(
            "theme = \"purple\"\nlocalUserName = \"  Ada   Lovelace  \"\nsosein_cloud_enabled = true\nunknown = \"ignored\"\n",
        );

        assert_eq!(settings.theme, DEFAULT_THEME);
        assert_eq!(settings.local_user_name, "Ada Lovelace");
        assert!(settings.sosein_cloud_enabled);
        assert_eq!(
            settings_toml(&AppSettings {
                theme: "DARK".to_string(),
                local_user_name: "  Grace   Hopper  ".to_string(),
                sosein_cloud_enabled: true,
            }),
            "theme = \"dark\"\nlocal_user_name = \"Grace Hopper\"\nsosein_cloud_enabled = true\n"
        );
    }

    #[cfg(not(target_os = "ios"))]
    #[test]
    fn builds_and_parses_sosein_oauth_loopback_values() {
        assert_eq!(
            normalized_sosein_api_base(" https://api.sosein.ai/ "),
            Ok("https://api.sosein.ai".to_string())
        );
        assert!(normalized_sosein_api_base("margin://oauth").is_err());
        assert_eq!(
            percent_encode_query_value("http://127.0.0.1:49152/oauth/callback"),
            "http%3A%2F%2F127.0.0.1%3A49152%2Foauth%2Fcallback"
        );
        let callback_target = "/oauth/callback?state=ignored&handoff_code=abc%2B123";

        assert!(sosein_oauth_callback_path_matches(callback_target));
        assert!(!sosein_oauth_callback_path_matches(
            "/oauth/callback-extra?handoff_code=abc%2B123"
        ));
        assert_eq!(
            sosein_api_url("https://api.sosein.ai", "/v1/auth/oauth/handoff/exchange"),
            Ok("https://api.sosein.ai/v1/auth/oauth/handoff/exchange".to_string())
        );
        assert!(normalized_sosein_api_path("https://api.sosein.ai/v1/documents").is_err());
        assert_eq!(
            oauth_query_value(callback_target, "handoff_code"),
            Ok(Some("abc+123".to_string()))
        );
    }

    #[cfg(not(target_os = "ios"))]
    #[test]
    fn parses_recent_document_and_insert_menu_ids() {
        assert_eq!(recent_document_menu_index("file_recent_123456_4"), Some(4));
        assert_eq!(recent_document_menu_index("file_recent__4"), None);
        assert_eq!(recent_document_menu_index("file_recent_nonce_4"), None);
        assert_eq!(
            recent_document_menu_index("file_clear_recent_123456_4"),
            None
        );

        assert_eq!(insert_payload("insert_table"), Some("table"));
        assert_eq!(insert_payload("insert_tasks"), Some("tasks"));
        assert_eq!(insert_payload("insert_bullets"), Some("bullets"));
        assert_eq!(insert_payload("insert_numbers"), Some("numbers"));
        assert_eq!(insert_payload("insert_image"), None);
    }

    #[cfg(not(target_os = "ios"))]
    #[test]
    fn filters_watched_document_events_to_relevant_path_and_kind() {
        use notify::event::{DataChange, ModifyKind};

        let watched = PathBuf::from("/tmp/Watched.md");
        let other = PathBuf::from("/tmp/Other.md");
        let changed_watched = Event {
            kind: EventKind::Modify(ModifyKind::Data(DataChange::Content)),
            paths: vec![watched.clone()],
            attrs: Default::default(),
        };
        let changed_other = Event {
            kind: EventKind::Modify(ModifyKind::Data(DataChange::Content)),
            paths: vec![other],
            attrs: Default::default(),
        };
        let irrelevant_kind = Event {
            kind: EventKind::Other,
            paths: vec![watched.clone()],
            attrs: Default::default(),
        };

        assert!(should_emit_document_change(&changed_watched, &watched));
        assert!(!should_emit_document_change(&changed_other, &watched));
        assert!(!should_emit_document_change(&irrelevant_kind, &watched));
    }
}

#[cfg(target_os = "ios")]
fn ios_file_picker_message() -> String {
    "Native document picking is not available in the iOS preview yet.".to_string()
}

fn read_settings_file(app: &AppHandle) -> Result<AppSettings, String> {
    let path = settings_path(app)?;
    if !path.exists() {
        return Ok(AppSettings::default());
    }

    let contents = fs::read_to_string(&path)
        .map_err(|err| format!("Unable to read {}: {err}", display_name(&path)))?;
    Ok(parse_settings_toml(&contents))
}

fn settings_path(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(app
        .path()
        .app_config_dir()
        .map_err(|err| format!("Unable to locate app config directory: {err}"))?
        .join(SETTINGS_FILE_NAME))
}

fn recent_documents_path(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(app_state_dir(app)?.join(RECENT_DOCUMENTS_FILE_NAME))
}

fn app_state_dir(app: &AppHandle) -> Result<PathBuf, String> {
    #[cfg(target_os = "linux")]
    {
        linux_app_state_dir(app)
    }

    #[cfg(not(target_os = "linux"))]
    {
        app.path()
            .app_data_dir()
            .map_err(|err| format!("Unable to locate app data directory: {err}"))
    }
}

#[cfg(target_os = "linux")]
fn linux_app_state_dir(app: &AppHandle) -> Result<PathBuf, String> {
    if let Some(path) = env::var_os("XDG_STATE_HOME").map(PathBuf::from) {
        if path.is_absolute() {
            return Ok(path.join(&app.config().identifier));
        }
    }

    env::var_os("HOME")
        .map(PathBuf::from)
        .map(|home| {
            home.join(".local")
                .join("state")
                .join(&app.config().identifier)
        })
        .ok_or_else(|| "Unable to locate home directory for app state".to_string())
}

#[cfg(not(target_os = "ios"))]
fn run_sosein_oauth_loopback(server_url: String) -> Result<SoseinOAuthSession, String> {
    let api_base = normalized_sosein_api_base(&server_url)?;
    let listener = TcpListener::bind(("127.0.0.1", 0))
        .map_err(|err| format!("Unable to start Sosein Cloud login listener: {err}"))?;
    let port = listener
        .local_addr()
        .map_err(|err| format!("Unable to read Sosein Cloud login listener address: {err}"))?
        .port();
    let callback_url = format!("http://127.0.0.1:{port}/oauth/callback");
    let login_url = format!(
        "{api_base}/v1/auth/oauth/google/login?return_to={}",
        percent_encode_query_value(&callback_url)
    );

    listener
        .set_nonblocking(true)
        .map_err(|err| format!("Unable to configure Sosein Cloud login listener: {err}"))?;
    open_system_browser(&login_url)?;
    let handoff_code = wait_for_sosein_oauth_callback(listener)?;

    exchange_sosein_oauth_handoff(&api_base, &handoff_code)
}

#[cfg(not(target_os = "ios"))]
fn wait_for_sosein_oauth_callback(listener: TcpListener) -> Result<String, String> {
    let deadline = Instant::now() + SOSEIN_OAUTH_TIMEOUT;

    loop {
        match listener.accept() {
            Ok((stream, _address)) => {
                if let Some(handoff_code) = handle_sosein_oauth_connection(stream)? {
                    return Ok(handoff_code);
                }
            }
            Err(err) if err.kind() == std::io::ErrorKind::WouldBlock => {
                if Instant::now() >= deadline {
                    return Err("Timed out waiting for Sosein Cloud login.".to_string());
                }

                thread::sleep(Duration::from_millis(50));
            }
            Err(err) => {
                return Err(format!(
                    "Unable to accept Sosein Cloud login callback: {err}"
                ))
            }
        }
    }
}

#[cfg(not(target_os = "ios"))]
fn handle_sosein_oauth_connection(mut stream: TcpStream) -> Result<Option<String>, String> {
    stream
        .set_read_timeout(Some(Duration::from_secs(3)))
        .map_err(|err| format!("Unable to configure Sosein Cloud login callback: {err}"))?;

    let mut buffer = [0_u8; 8192];
    let read = stream
        .read(&mut buffer)
        .map_err(|err| format!("Unable to read Sosein Cloud login callback: {err}"))?;
    let request = String::from_utf8_lossy(&buffer[..read]);
    let request_line = request.lines().next().unwrap_or("");
    let mut request_parts = request_line.split_whitespace();
    let method = request_parts.next().unwrap_or("");
    let target = request_parts.next().unwrap_or("");

    if method != "GET" {
        write_oauth_http_response(
            &mut stream,
            "405 Method Not Allowed",
            "Margin can only receive Sosein Cloud OAuth GET callbacks.",
        )?;

        return Ok(None);
    }

    if !sosein_oauth_callback_path_matches(target) {
        write_oauth_http_response(
            &mut stream,
            "404 Not Found",
            "Unknown Margin OAuth callback.",
        )?;

        return Ok(None);
    }

    if let Some(error) = oauth_query_value(target, "error")? {
        write_oauth_http_response(
            &mut stream,
            "400 Bad Request",
            "Sosein Cloud login did not complete.",
        )?;

        return Err(format!("Sosein Cloud login failed: {error}"));
    }

    let Some(handoff_code) = oauth_query_value(target, "handoff_code")? else {
        write_oauth_http_response(
            &mut stream,
            "400 Bad Request",
            "Sosein Cloud login callback did not include a handoff code.",
        )?;

        return Err("Sosein Cloud login callback did not include a handoff code.".to_string());
    };

    write_oauth_http_response(
        &mut stream,
        "200 OK",
        "Sosein Cloud login finished. You can return to Margin.",
    )?;

    Ok(Some(handoff_code))
}

#[cfg(not(target_os = "ios"))]
fn write_oauth_http_response(
    stream: &mut TcpStream,
    status: &str,
    message: &str,
) -> Result<(), String> {
    let body = format!(
        "<!doctype html><meta charset=\"utf-8\"><title>Margin</title><body><p>{}</p></body>",
        html_escape(message)
    );
    let response = format!(
        "HTTP/1.1 {status}\r\ncontent-type: text/html; charset=utf-8\r\ncontent-length: {}\r\nconnection: close\r\n\r\n{body}",
        body.len()
    );

    stream
        .write_all(response.as_bytes())
        .map_err(|err| format!("Unable to write Sosein Cloud login response: {err}"))?;
    let _ = stream.flush();

    Ok(())
}

#[cfg(not(target_os = "ios"))]
fn normalized_sosein_api_base(server_url: &str) -> Result<String, String> {
    let trimmed = server_url.trim().trim_end_matches('/');

    if trimmed.starts_with("https://") || trimmed.starts_with("http://") {
        Ok(trimmed.to_string())
    } else {
        Err("Sosein Cloud server URL must start with http:// or https://.".to_string())
    }
}

#[cfg(not(target_os = "ios"))]
fn sosein_oauth_callback_path_matches(target: &str) -> bool {
    target.split_once('?').map_or(target, |(path, _query)| path) == "/oauth/callback"
}

#[cfg(not(target_os = "ios"))]
fn exchange_sosein_oauth_handoff(
    api_base: &str,
    handoff_code: &str,
) -> Result<SoseinOAuthSession, String> {
    let client = reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()
        .map_err(|err| format!("Unable to prepare Sosein Cloud login exchange: {err}"))?;
    let response = client
        .post(sosein_api_url(api_base, "/v1/auth/oauth/handoff/exchange")?)
        .json(&SoseinOAuthHandoffExchangeRequest { handoff_code })
        .send()
        .map_err(|err| format!("Unable to exchange Sosein Cloud login handoff: {err}"))?;
    let status = response.status();
    let body_text = response
        .text()
        .map_err(|err| format!("Unable to read Sosein Cloud login exchange response: {err}"))?;

    if !status.is_success() {
        return Err(format!(
            "Sosein Cloud login exchange failed with {}{}",
            status.as_u16(),
            compact_response_suffix(&body_text)
        ));
    }

    serde_json::from_str(&body_text)
        .map_err(|err| format!("Unable to parse Sosein Cloud login exchange response: {err}"))
}

#[cfg(not(target_os = "ios"))]
fn run_sosein_api_request(
    server_url: String,
    method: String,
    path: String,
    session_token: Option<String>,
    body: Option<serde_json::Value>,
) -> Result<NativeSoseinApiResponse, String> {
    let api_base = normalized_sosein_api_base(&server_url)?;
    let path = normalized_sosein_api_path(&path)?;
    let client = reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(30))
        .build()
        .map_err(|err| format!("Unable to prepare Sosein Cloud request: {err}"))?;
    let method = method.trim().to_ascii_uppercase();
    let mut request = match method.as_str() {
        "GET" => client.get(sosein_api_url(&api_base, &path)?),
        "POST" => client.post(sosein_api_url(&api_base, &path)?),
        _ => return Err("Sosein Cloud request method must be GET or POST.".to_string()),
    };

    if let Some(token) = session_token.filter(|token| !token.trim().is_empty()) {
        request = request.bearer_auth(token);
    }

    if let Some(body) = body {
        request = request.json(&body);
    }

    let response = request
        .send()
        .map_err(|err| format!("Unable to send Sosein Cloud request: {err}"))?;
    let status = response.status().as_u16();
    let body_text = response
        .text()
        .map_err(|err| format!("Unable to read Sosein Cloud response: {err}"))?;
    let body = if body_text.trim().is_empty() {
        None
    } else {
        serde_json::from_str(&body_text).ok()
    };

    Ok(NativeSoseinApiResponse {
        status,
        body,
        body_text,
    })
}

#[cfg(not(target_os = "ios"))]
fn normalized_sosein_api_path(path: &str) -> Result<String, String> {
    let trimmed = path.trim();

    if !trimmed.starts_with("/v1/")
        || trimmed.contains("://")
        || trimmed
            .chars()
            .any(|character| character == '\r' || character == '\n')
    {
        return Err("Sosein Cloud request path must be a /v1/ API path.".to_string());
    }

    Ok(trimmed.to_string())
}

#[cfg(not(target_os = "ios"))]
fn sosein_api_url(api_base: &str, path: &str) -> Result<String, String> {
    let path = normalized_sosein_api_path(path)?;

    Ok(format!("{api_base}{path}"))
}

#[cfg(not(target_os = "ios"))]
fn compact_response_suffix(body: &str) -> String {
    let compact = body.split_whitespace().collect::<Vec<_>>().join(" ");

    if compact.is_empty() {
        String::new()
    } else {
        format!(": {}", compact.chars().take(240).collect::<String>())
    }
}

#[cfg(not(target_os = "ios"))]
fn oauth_query_value(target: &str, key: &str) -> Result<Option<String>, String> {
    let Some((_, query)) = target.split_once('?') else {
        return Ok(None);
    };

    for pair in query.split('&') {
        let (raw_key, raw_value) = pair.split_once('=').unwrap_or((pair, ""));

        if percent_decode_query_value(raw_key)? == key {
            return Ok(Some(percent_decode_query_value(raw_value)?));
        }
    }

    Ok(None)
}

#[cfg(not(target_os = "ios"))]
fn percent_encode_query_value(value: &str) -> String {
    let mut encoded = String::new();

    for byte in value.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                encoded.push(byte as char);
            }
            _ => encoded.push_str(&format!("%{byte:02X}")),
        }
    }

    encoded
}

#[cfg(not(target_os = "ios"))]
fn percent_decode_query_value(value: &str) -> Result<String, String> {
    let mut decoded = Vec::with_capacity(value.len());
    let bytes = value.as_bytes();
    let mut index = 0;

    while index < bytes.len() {
        match bytes[index] {
            b'+' => {
                decoded.push(b' ');
                index += 1;
            }
            b'%' if index + 2 < bytes.len() => {
                let hex = &value[index + 1..index + 3];
                let byte = u8::from_str_radix(hex, 16)
                    .map_err(|_| "Sosein Cloud login callback included invalid URL encoding.")?;

                decoded.push(byte);
                index += 3;
            }
            b'%' => {
                return Err(
                    "Sosein Cloud login callback included invalid URL encoding.".to_string()
                );
            }
            byte => {
                decoded.push(byte);
                index += 1;
            }
        }
    }

    String::from_utf8(decoded)
        .map_err(|_| "Sosein Cloud login callback included invalid UTF-8.".to_string())
}

#[cfg(not(target_os = "ios"))]
fn html_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[cfg(all(not(target_os = "ios"), target_os = "macos"))]
fn open_system_browser(url: &str) -> Result<(), String> {
    command_status(Command::new("open").arg(url), "open")
}

#[cfg(all(not(target_os = "ios"), target_os = "windows"))]
fn open_system_browser(url: &str) -> Result<(), String> {
    command_status(Command::new("cmd").args(["/C", "start", "", url]), "start")
}

#[cfg(all(
    not(target_os = "ios"),
    not(target_os = "macos"),
    not(target_os = "windows")
))]
fn open_system_browser(url: &str) -> Result<(), String> {
    command_status(Command::new("xdg-open").arg(url), "xdg-open")
}

#[cfg(not(target_os = "ios"))]
fn command_status(command: &mut Command, command_name: &str) -> Result<(), String> {
    let status = command
        .status()
        .map_err(|err| format!("Unable to open Sosein Cloud login in browser: {err}"))?;

    if status.success() {
        Ok(())
    } else {
        Err(format!(
            "Unable to open Sosein Cloud login in browser with {command_name}."
        ))
    }
}

fn parse_settings_toml(contents: &str) -> AppSettings {
    let mut settings = AppSettings::default();

    for line in contents.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let Some((key, value)) = line.split_once('=') else {
            continue;
        };

        let value = settings_value(value);

        match key.trim() {
            "theme" => settings.theme = normalized_theme(&value).to_string(),
            "local_user_name" | "localUserName" => {
                settings.local_user_name = normalized_local_user_name(&value);
            }
            "sosein_cloud_enabled" | "soseinCloudEnabled" => {
                if let Some(enabled) = settings_bool_value(&value) {
                    settings.sosein_cloud_enabled = enabled;
                }
            }
            _ => {}
        }
    }

    settings
}

fn settings_toml(settings: &AppSettings) -> String {
    format!(
        "theme = {}\nlocal_user_name = {}\nsosein_cloud_enabled = {}\n",
        toml_string_literal(normalized_theme(&settings.theme)),
        toml_string_literal(&normalized_local_user_name(&settings.local_user_name)),
        settings.sosein_cloud_enabled
    )
}

fn settings_bool_value(value: &str) -> Option<bool> {
    let value = value.trim().to_ascii_lowercase();
    match value.as_str() {
        "1" | "true" | "yes" | "on" => Some(true),
        "0" | "false" | "no" | "off" => Some(false),
        _ => None,
    }
}

fn default_theme() -> String {
    DEFAULT_THEME.to_string()
}

fn normalized_theme(theme: &str) -> &'static str {
    match theme.trim().to_ascii_lowercase().as_str() {
        "light" => "light",
        "dark" => "dark",
        _ => DEFAULT_THEME,
    }
}

fn normalized_local_user_name(name: &str) -> String {
    cleaned_local_user_name(name).unwrap_or_else(default_local_user_name)
}

fn default_local_user_name() -> String {
    os_local_user_name().unwrap_or_else(|| DEFAULT_LOCAL_USER_NAME.to_string())
}

#[cfg(target_os = "windows")]
fn os_local_user_name() -> Option<String> {
    env::var("USERNAME")
        .ok()
        .and_then(|name| cleaned_local_user_name(&name))
}

#[cfg(not(target_os = "windows"))]
fn os_local_user_name() -> Option<String> {
    env::var("USER")
        .ok()
        .and_then(|name| cleaned_local_user_name(&name))
}

fn cleaned_local_user_name(name: &str) -> Option<String> {
    let name = name.split_whitespace().collect::<Vec<_>>().join(" ");

    if name.is_empty() {
        None
    } else {
        Some(name)
    }
}

fn settings_value(value: &str) -> String {
    let value = value.trim();

    if let Some(rest) = value.strip_prefix('"') {
        return quoted_settings_value(rest, '"', true);
    }

    if let Some(rest) = value.strip_prefix('\'') {
        return quoted_settings_value(rest, '\'', false);
    }

    value.split('#').next().unwrap_or("").trim().to_string()
}

fn quoted_settings_value(value: &str, quote: char, escaped: bool) -> String {
    let mut output = String::new();
    let mut chars = value.chars();

    while let Some(character) = chars.next() {
        if character == quote {
            break;
        }

        if escaped && character == '\\' {
            let Some(escaped_character) = chars.next() else {
                break;
            };

            output.push(match escaped_character {
                'n' => '\n',
                'r' => '\r',
                't' => '\t',
                '"' => '"',
                '\\' => '\\',
                other => other,
            });

            continue;
        }

        output.push(character);
    }

    output
}

fn toml_string_literal(value: &str) -> String {
    let mut output = String::from("\"");

    for character in value.chars() {
        match character {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            other => output.push(other),
        }
    }

    output.push('"');
    output
}

fn read_recent_documents_file(app: &AppHandle) -> Result<Vec<RecentDocumentEntry>, String> {
    let path = recent_documents_path(app)?;
    if !path.exists() {
        return Ok(Vec::new());
    }

    let contents = fs::read_to_string(&path)
        .map_err(|err| format!("Unable to read {}: {err}", display_name(&path)))?;
    let entries = serde_json::from_str::<Vec<RecentDocumentEntry>>(&contents)
        .map_err(|err| format!("Unable to parse {}: {err}", display_name(&path)))?;

    Ok(normalized_recent_documents(entries))
}

fn write_recent_documents_file(
    app: &AppHandle,
    entries: &[RecentDocumentEntry],
) -> Result<(), String> {
    let path = recent_documents_path(app)?;

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("Unable to create app data directory: {err}"))?;
    }

    let contents = serde_json::to_string_pretty(entries)
        .map_err(|err| format!("Unable to encode recent documents: {err}"))?;

    fs::write(&path, contents)
        .map_err(|err| format!("Unable to write {}: {err}", display_name(&path)))
}

fn normalized_recent_documents(entries: Vec<RecentDocumentEntry>) -> Vec<RecentDocumentEntry> {
    let mut seen_paths = HashSet::new();
    let mut normalized = Vec::new();

    for entry in entries {
        let path = entry.path.trim();

        if path.is_empty() || !seen_paths.insert(path.to_string()) {
            continue;
        }

        let title = if entry.title.trim().is_empty() {
            display_name(Path::new(path))
        } else {
            entry.title.trim().to_string()
        };

        normalized.push(RecentDocumentEntry {
            title,
            path: path.to_string(),
            opened_at: entry.opened_at,
        });

        if normalized.len() >= RECENT_DOCUMENT_LIMIT {
            break;
        }
    }

    normalized
}

fn read_markdown_document_from_path(path: &Path) -> Result<NativeMarkdownDocument, String> {
    ensure_markdown_path(path)?;
    let markdown = fs::read_to_string(path)
        .map_err(|err| format!("Unable to read {}: {err}", display_name(path)))?;
    Ok(markdown_document_payload(path, markdown))
}

fn read_directory_tree_from_path(path: &Path) -> Result<NativeDirectoryTree, String> {
    let path = path
        .canonicalize()
        .map_err(|err| format!("Unable to open {}: {err}", path.display()))?;

    if !path.is_dir() {
        return Err("Margin can open a folder or Markdown document.".to_string());
    }

    let ignore_rules = DirectoryIgnoreRules::for_directory(&path);
    let mut remaining_entries = DIRECTORY_TREE_MAX_ENTRIES;
    let entries = read_directory_entries(&path, 0, &mut remaining_entries, &ignore_rules)?;

    Ok(NativeDirectoryTree {
        name: directory_display_name(&path),
        path: path.to_string_lossy().to_string(),
        entries,
    })
}

fn read_directory_entries(
    path: &Path,
    depth: usize,
    remaining_entries: &mut usize,
    ignore_rules: &DirectoryIgnoreRules,
) -> Result<Vec<NativeDirectoryEntry>, String> {
    if depth >= DIRECTORY_TREE_MAX_DEPTH || *remaining_entries == 0 {
        return Ok(Vec::new());
    }

    let mut entries = Vec::new();

    for entry in
        fs::read_dir(path).map_err(|err| format!("Unable to read {}: {err}", path.display()))?
    {
        if *remaining_entries == 0 {
            break;
        }

        let entry = match entry {
            Ok(entry) => entry,
            Err(err) => {
                eprintln!(
                    "Unable to inspect a directory entry in {}: {err}",
                    path.display()
                );
                continue;
            }
        };

        let file_type = match entry.file_type() {
            Ok(file_type) => file_type,
            Err(err) => {
                eprintln!("Unable to inspect {}: {err}", entry.path().display());
                continue;
            }
        };

        let entry_path = entry.path();
        let is_directory = file_type.is_dir();

        if ignore_rules.is_ignored(&entry_path, is_directory) {
            continue;
        }

        let name = display_name(&entry_path);
        let kind = if is_directory {
            NativeDirectoryEntryKind::Directory
        } else if is_markdown_path(&entry_path) {
            NativeDirectoryEntryKind::Markdown
        } else {
            NativeDirectoryEntryKind::File
        };
        let canonical_path = entry_path.canonicalize().unwrap_or(entry_path);

        *remaining_entries -= 1;

        entries.push(NativeDirectoryEntry {
            path: canonical_path.to_string_lossy().to_string(),
            name,
            kind,
            children: Vec::new(),
        });
    }

    sort_directory_entries(&mut entries);

    if depth + 1 < DIRECTORY_TREE_MAX_DEPTH {
        for entry in entries.iter_mut() {
            if *remaining_entries == 0 {
                break;
            }

            if entry.kind != NativeDirectoryEntryKind::Directory {
                continue;
            }

            let entry_path = Path::new(&entry.path);
            let child_ignore_rules = ignore_rules.with_directory(entry_path);

            entry.children = read_directory_entries(
                entry_path,
                depth + 1,
                remaining_entries,
                &child_ignore_rules,
            )
            .unwrap_or_else(|err| {
                eprintln!("{err}");
                Vec::new()
            });
        }
    }

    Ok(entries)
}

fn sort_directory_entries(entries: &mut [NativeDirectoryEntry]) {
    entries.sort_by(|left, right| {
        directory_entry_rank(left.kind)
            .cmp(&directory_entry_rank(right.kind))
            .then_with(|| left.name.to_lowercase().cmp(&right.name.to_lowercase()))
            .then_with(|| left.name.cmp(&right.name))
    });
}

fn directory_entry_rank(kind: NativeDirectoryEntryKind) -> u8 {
    match kind {
        NativeDirectoryEntryKind::Directory => 0,
        NativeDirectoryEntryKind::Markdown => 1,
        NativeDirectoryEntryKind::File => 2,
    }
}

#[cfg(test)]
mod directory_tree_tests {
    use super::*;

    #[test]
    fn directory_tree_excludes_gitignored_entries() {
        let test_id = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time is after unix epoch")
            .as_nanos();
        let root = env::temp_dir().join(format!(
            "margin-directory-tree-gitignore-{}-{test_id}",
            std::process::id()
        ));

        if root.exists() {
            fs::remove_dir_all(&root).expect("stale test directory can be removed");
        }

        fs::create_dir_all(root.join("ignored-dir")).expect("ignored directory can be created");
        fs::create_dir_all(root.join("nested")).expect("nested directory can be created");
        fs::write(
            root.join(".gitignore"),
            "ignored.md\nignored-dir/\n*.tmp\n!keep.tmp\nnested/ignored-from-root.md\n",
        )
        .expect("root gitignore can be written");
        fs::write(root.join("visible.md"), "# Visible").expect("visible file can be written");
        fs::write(root.join("ignored.md"), "# Ignored").expect("ignored file can be written");
        fs::write(root.join("scratch.tmp"), "ignored").expect("ignored tmp can be written");
        fs::write(root.join("keep.tmp"), "visible").expect("unignored tmp can be written");
        fs::write(root.join("ignored-dir").join("visible.md"), "# Hidden")
            .expect("file in ignored directory can be written");
        fs::write(
            root.join("nested").join(".gitignore"),
            "nested-ignored.md\n!nested-keep.tmp\n",
        )
        .expect("nested gitignore can be written");
        fs::write(root.join("nested").join("nested-visible.md"), "# Nested")
            .expect("nested visible file can be written");
        fs::write(
            root.join("nested").join("nested-ignored.md"),
            "# Nested hidden",
        )
        .expect("nested ignored file can be written");
        fs::write(
            root.join("nested").join("ignored-from-root.md"),
            "# Root hidden",
        )
        .expect("root ignored nested file can be written");
        fs::write(root.join("nested").join("nested-keep.tmp"), "visible")
            .expect("nested unignored tmp can be written");

        let tree = read_directory_tree_from_path(&root).expect("directory tree can be read");
        let root_names = entry_names(&tree.entries);

        assert!(root_names.contains(&"nested".to_string()));
        assert!(root_names.contains(&"visible.md".to_string()));
        assert!(root_names.contains(&"keep.tmp".to_string()));
        assert!(!root_names.contains(&"ignored.md".to_string()));
        assert!(!root_names.contains(&"ignored-dir".to_string()));
        assert!(!root_names.contains(&"scratch.tmp".to_string()));

        let nested = tree
            .entries
            .iter()
            .find(|entry| entry.name == "nested")
            .expect("nested directory is visible");
        let nested_names = entry_names(&nested.children);

        assert!(nested_names.contains(&"nested-visible.md".to_string()));
        assert!(nested_names.contains(&"nested-keep.tmp".to_string()));
        assert!(!nested_names.contains(&"nested-ignored.md".to_string()));
        assert!(!nested_names.contains(&"ignored-from-root.md".to_string()));

        fs::remove_dir_all(&root).expect("test directory can be removed");
    }

    fn entry_names(entries: &[NativeDirectoryEntry]) -> Vec<String> {
        entries.iter().map(|entry| entry.name.clone()).collect()
    }
}

#[cfg(not(target_os = "ios"))]
fn should_emit_document_change(event: &Event, watched_path: &Path) -> bool {
    let relevant_kind = matches!(
        &event.kind,
        EventKind::Any | EventKind::Create(_) | EventKind::Modify(_) | EventKind::Remove(_)
    );

    relevant_kind && event.paths.iter().any(|path| path == watched_path)
}

fn markdown_document_payload(path: &Path, markdown: String) -> NativeMarkdownDocument {
    let path = path.canonicalize().unwrap_or_else(|_| path.to_path_buf());

    NativeMarkdownDocument {
        name: display_name(&path),
        path: path.to_string_lossy().to_string(),
        markdown,
    }
}

fn ensure_markdown_path(path: &Path) -> Result<(), String> {
    if is_markdown_path(path) {
        Ok(())
    } else {
        Err("Margin can open Markdown, Markdown-like, or plain text documents.".to_string())
    }
}

fn normalized_save_path(mut path: PathBuf) -> PathBuf {
    if path.extension().is_none() {
        path.set_extension("md");
    }
    path
}

fn display_name(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("Untitled.md")
        .to_string()
}

fn directory_display_name(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .map(str::to_string)
        .unwrap_or_else(|| path.display().to_string())
}

#[cfg(not(target_os = "ios"))]
fn clear_submenu<R: Runtime>(menu: &Submenu<R>) -> Result<(), String> {
    let item_count = menu.items().map_err(|err| err.to_string())?.len();
    for index in (0..item_count).rev() {
        menu.remove_at(index).map_err(|err| err.to_string())?;
    }
    Ok(())
}

#[cfg(not(target_os = "ios"))]
fn recent_menu_label(title: &str) -> String {
    const MAX_CHARS: usize = 52;
    if title.chars().count() <= MAX_CHARS {
        return title.to_string();
    }

    let mut label = title.chars().take(MAX_CHARS - 1).collect::<String>();
    label.push_str("...");
    label
}

#[cfg(not(target_os = "ios"))]
fn recent_menu_nonce() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_nanos())
        .unwrap_or_default()
}

#[cfg(not(target_os = "ios"))]
fn recent_document_menu_index(menu_id: &str) -> Option<usize> {
    let suffix = menu_id.strip_prefix(RECENT_MENU_ITEM_PREFIX)?;

    let (nonce, index) = suffix.rsplit_once('_')?;

    if nonce.is_empty() || !nonce.chars().all(|character| character.is_ascii_digit()) {
        return None;
    }

    index.parse().ok()
}

fn dispatch_native_open_urls(app: &AppHandle, urls: Vec<String>) {
    if urls.is_empty() {
        return;
    }

    #[cfg(not(target_os = "ios"))]
    {
        if let Some(window) = app.get_webview_window("main") {
            let _ = window.show();
            let _ = window.set_focus();
        }
    }

    let state = app.state::<NativeOpenState>();
    if state.frontend_ready.load(Ordering::SeqCst) {
        let _ = app.emit("margin://open-urls", urls);
        return;
    }

    let mut pending_urls = state
        .pending_urls
        .lock()
        .expect("pending open URL state poisoned");
    pending_urls.extend(urls);
}

#[cfg(not(target_os = "ios"))]
fn launch_urls_from_args(args: Vec<String>) -> Vec<String> {
    args.into_iter()
        .skip(1)
        .filter_map(launch_url_from_arg)
        .collect()
}

#[cfg(not(target_os = "ios"))]
fn launch_url_from_arg(arg: String) -> Option<String> {
    if arg.starts_with("margin://") || arg.starts_with("file://") {
        return Some(arg);
    }

    let path = PathBuf::from(&arg);
    if !path.exists() || (!path.is_dir() && !is_markdown_path(&path)) {
        return None;
    }

    Url::from_file_path(path).ok().map(|url| url.to_string())
}

fn is_markdown_path(path: &Path) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .map(|extension| {
            matches!(
                extension.to_ascii_lowercase().as_str(),
                "md" | "markdown" | "txt"
            )
        })
        .unwrap_or(false)
}

#[cfg(not(target_os = "ios"))]
fn insert_payload(menu_id: &str) -> Option<&'static str> {
    match menu_id {
        "insert_table" => Some("table"),
        "insert_tasks" => Some("tasks"),
        "insert_bullets" => Some("bullets"),
        "insert_numbers" => Some("numbers"),
        _ => None,
    }
}

#[cfg(not(target_os = "ios"))]
fn insert_menu_position() -> usize {
    #[cfg(target_os = "macos")]
    {
        3
    }
    #[cfg(any(
        target_os = "linux",
        target_os = "dragonfly",
        target_os = "freebsd",
        target_os = "netbsd",
        target_os = "openbsd"
    ))]
    {
        1
    }
    #[cfg(not(any(
        target_os = "macos",
        target_os = "linux",
        target_os = "dragonfly",
        target_os = "freebsd",
        target_os = "netbsd",
        target_os = "openbsd"
    )))]
    {
        2
    }
}

#[cfg(not(target_os = "ios"))]
fn tools_menu_position() -> usize {
    insert_menu_position() + 1
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default()
        .manage(NativeOpenState::default())
        .plugin(tauri_plugin_deep_link::init());

    #[cfg(not(target_os = "ios"))]
    let builder = builder
        .manage(WatchedDocumentState::default())
        .manage(RecentDocumentsMenuState::default());

    #[cfg(not(target_os = "ios"))]
    let builder = builder.plugin(tauri_plugin_single_instance::init(|app, args, _cwd| {
        dispatch_native_open_urls(app, launch_urls_from_args(args));
    }));

    #[cfg(not(target_os = "ios"))]
    let builder = builder.plugin(
        tauri_plugin_updater::Builder::new()
            .pubkey(UPDATER_PUBLIC_KEY)
            .build(),
    );

    let builder = builder.setup(|app| {
        #[cfg(not(target_os = "ios"))]
        {
            let menu = Menu::default(app.handle())?;
            let settings_item = MenuItem::with_id(
                app,
                "app_settings",
                "Settings...",
                true,
                Some("CmdOrCtrl+,"),
            )?;
            let check_updates_item = MenuItem::with_id(
                app,
                "app_check_updates",
                "Check for Updates...",
                true,
                None::<&str>,
            )?;
            let settings_separator = PredefinedMenuItem::separator(app)?;
            #[cfg(target_os = "macos")]
            let mut settings_item_added = false;
            #[cfg(not(target_os = "macos"))]
            let settings_item_added = false;

            #[cfg(target_os = "macos")]
            if let Some(app_menu) = menu
                .items()?
                .first()
                .and_then(|item| item.as_submenu().cloned())
            {
                app_menu.insert_items(&[&settings_item, &check_updates_item], 1)?;
                settings_item_added = true;
            }

            let new_file = MenuItem::with_id(app, "file_new", "New", true, Some("CmdOrCtrl+N"))?;
            let quick_open = MenuItem::with_id(
                app,
                "file_quick_open",
                "Quick Open...",
                true,
                Some("CmdOrCtrl+P"),
            )?;
            let open_file =
                MenuItem::with_id(app, "file_open", "Open...", true, Some("CmdOrCtrl+O"))?;
            let open_folder = MenuItem::with_id(
                app,
                "file_open_folder",
                "Open Folder...",
                true,
                Some("CmdOrCtrl+Shift+O"),
            )?;
            let recent_empty = MenuItem::with_id(
                app,
                "file_recent_empty",
                "No Recent Documents",
                false,
                None::<&str>,
            )?;
            let open_recent = Submenu::with_id_and_items(
                app,
                RECENT_MENU_ID,
                "Open Recent",
                true,
                &[&recent_empty],
            )?;
            let save_file = MenuItem::with_id(app, "file_save", "Save", true, Some("CmdOrCtrl+S"))?;
            let save_file_as = MenuItem::with_id(
                app,
                "file_save_as",
                "Save As...",
                true,
                Some("CmdOrCtrl+Shift+S"),
            )?;
            let print_file = MenuItem::with_id(app, "file_print", "Print...", true, None::<&str>)?;
            let file_open_separator = PredefinedMenuItem::separator(app)?;
            let file_save_separator = PredefinedMenuItem::separator(app)?;
            let close_tab = MenuItem::with_id(
                app,
                "file_close_tab",
                "Close Tab",
                true,
                Some("CmdOrCtrl+W"),
            )?;
            let close_window = MenuItem::with_id(
                app,
                "file_close_window",
                "Close Window",
                true,
                Some("CmdOrCtrl+Shift+W"),
            )?;
            if let Some(file_menu) = menu.items()?.into_iter().find_map(|item| {
                item.as_submenu()
                    .cloned()
                    .filter(|submenu| submenu.text().map(|text| text == "File").unwrap_or(false))
            }) {
                let item_count = file_menu.items()?.len();
                for index in (0..item_count).rev() {
                    file_menu.remove_at(index)?;
                }
                file_menu.append_items(&[
                    &new_file,
                    &quick_open,
                    &open_file,
                    &open_folder,
                    &open_recent,
                    &file_open_separator,
                    &save_file,
                    &save_file_as,
                    &print_file,
                    &file_save_separator,
                    &close_tab,
                    &close_window,
                ])?;

                if !settings_item_added {
                    file_menu.insert_items(
                        &[&settings_item, &check_updates_item, &settings_separator],
                        0,
                    )?;
                }
            }

            let find_separator = PredefinedMenuItem::separator(app)?;
            let command_palette = MenuItem::with_id(
                app,
                "edit_command_palette",
                "Command Palette...",
                true,
                Some("CmdOrCtrl+Shift+P"),
            )?;
            let find = MenuItem::with_id(app, "edit_find", "Find", true, Some("CmdOrCtrl+F"))?;
            let find_and_replace = MenuItem::with_id(
                app,
                "edit_find_and_replace",
                "Find and Replace...",
                true,
                Some("CmdOrCtrl+Alt+F"),
            )?;
            let find_next = MenuItem::with_id(
                app,
                "edit_find_next",
                "Find Next",
                true,
                Some("CmdOrCtrl+G"),
            )?;
            let find_previous = MenuItem::with_id(
                app,
                "edit_find_previous",
                "Find Previous",
                true,
                Some("CmdOrCtrl+Shift+G"),
            )?;
            if let Some(edit_menu) = menu.items()?.into_iter().find_map(|item| {
                item.as_submenu()
                    .cloned()
                    .filter(|submenu| submenu.text().map(|text| text == "Edit").unwrap_or(false))
            }) {
                edit_menu.append_items(&[
                    &command_palette,
                    &find_separator,
                    &find,
                    &find_and_replace,
                    &find_next,
                    &find_previous,
                ])?;
            }

            let insert_comment = MenuItem::with_id(
                app,
                "insert_comment",
                "Comment",
                true,
                Some("CmdOrCtrl+Alt+M"),
            )?;
            let insert_comment_separator = PredefinedMenuItem::separator(app)?;
            let insert_table = MenuItem::with_id(
                app,
                "insert_table",
                "Table",
                true,
                Some("CmdOrCtrl+Shift+T"),
            )?;
            let insert_tasks = MenuItem::with_id(
                app,
                "insert_tasks",
                "Task List",
                true,
                Some("CmdOrCtrl+Shift+X"),
            )?;
            let insert_bullets = MenuItem::with_id(
                app,
                "insert_bullets",
                "Bulleted List",
                true,
                Some("CmdOrCtrl+Shift+8"),
            )?;
            let insert_numbers = MenuItem::with_id(
                app,
                "insert_numbers",
                "Numbered List",
                true,
                Some("CmdOrCtrl+Shift+7"),
            )?;
            let insert_menu = Submenu::with_id_and_items(
                app,
                "insert",
                "Insert",
                true,
                &[
                    &insert_comment,
                    &insert_comment_separator,
                    &insert_table,
                    &insert_tasks,
                    &insert_bullets,
                    &insert_numbers,
                ],
            )?;

            menu.insert(&insert_menu, insert_menu_position())?;

            let word_count =
                MenuItem::with_id(app, "tools_word_count", "Word Count...", true, None::<&str>)?;
            let install_cli_item = MenuItem::with_id(
                app,
                "tools_install_cli",
                "Install 'margin' Command...",
                true,
                None::<&str>,
            )?;
            let tools_separator = PredefinedMenuItem::separator(app)?;
            let tools_menu = Submenu::with_id_and_items(
                app,
                "tools",
                "Tools",
                true,
                &[&word_count, &tools_separator, &install_cli_item],
            )?;

            menu.insert(&tools_menu, tools_menu_position())?;

            let toggle_file_tree = MenuItem::with_id(
                app,
                "view_toggle_file_tree",
                "Toggle File Tree",
                true,
                Some("CmdOrCtrl+B"),
            )?;
            if let Some(view_menu) = menu.items()?.into_iter().find_map(|item| {
                item.as_submenu()
                    .cloned()
                    .filter(|submenu| submenu.text().map(|text| text == "View").unwrap_or(false))
            }) {
                view_menu.append(&toggle_file_tree)?;
            } else {
                let view_menu =
                    Submenu::with_id_and_items(app, "view", "View", true, &[&toggle_file_tree])?;
                menu.append(&view_menu)?;
            }

            if let Some(window_menu) = menu.items()?.into_iter().find_map(|item| {
                item.as_submenu()
                    .cloned()
                    .filter(|submenu| submenu.text().map(|text| text == "Window").unwrap_or(false))
            }) {
                let item_count = window_menu.items()?.len();
                for index in (0..item_count).rev() {
                    window_menu.remove_at(index)?;
                }

                let previous_tab = MenuItem::with_id(
                    app,
                    "window_previous_tab",
                    "Show Previous Tab",
                    true,
                    Some("CmdOrCtrl+Shift+["),
                )?;
                let next_tab = MenuItem::with_id(
                    app,
                    "window_next_tab",
                    "Show Next Tab",
                    true,
                    Some("CmdOrCtrl+Shift+]"),
                )?;
                let tab_separator = PredefinedMenuItem::separator(app)?;
                let minimize_window = PredefinedMenuItem::minimize(app, None)?;
                let maximize_window = PredefinedMenuItem::maximize(app, None)?;

                window_menu.append_items(&[
                    &previous_tab,
                    &next_tab,
                    &tab_separator,
                    &minimize_window,
                    &maximize_window,
                ])?;
            }

            app.set_menu(menu)?;

            let app_handle = app.handle().clone();
            let recent_menu_state = app.state::<RecentDocumentsMenuState>();

            *recent_menu_state
                .menu
                .lock()
                .expect("recent documents menu state poisoned") = Some(open_recent.clone());

            match read_recent_documents_file(&app_handle) {
                Ok(entries) if !entries.is_empty() => {
                    if let Err(err) =
                        set_recent_documents_menu_entries(&app_handle, &open_recent, &entries)
                    {
                        eprintln!("Unable to restore recent documents menu: {err}");
                    }
                }
                Err(err) => eprintln!("Unable to read recent documents: {err}"),
                _ => {}
            }

            dispatch_native_open_urls(&app_handle, launch_urls_from_args(env::args().collect()));
        }

        #[cfg(target_os = "ios")]
        {
            let _ = app;
        }

        Ok(())
    });

    #[cfg(not(target_os = "ios"))]
    let builder = builder.on_menu_event(|app, event| {
        let menu_id = event.id();
        if menu_id.as_ref() == "app_settings" {
            let _ = app.emit("margin://open-settings", ());
        } else if menu_id.as_ref() == "app_check_updates" {
            let _ = app.emit("margin://check-for-updates", ());
        } else if menu_id.as_ref() == "tools_word_count" {
            let _ = app.emit("margin://show-word-count", ());
        } else if menu_id.as_ref() == "tools_install_cli" {
            show_cli_install_result(install_margin_cli());
        } else if menu_id.as_ref() == "file_new" {
            let _ = app.emit("margin://new-document", ());
        } else if menu_id.as_ref() == "file_quick_open" {
            let _ = app.emit("margin://quick-open-document", ());
        } else if menu_id.as_ref() == "file_open" {
            let _ = app.emit("margin://open-document", ());
        } else if menu_id.as_ref() == "file_open_folder" {
            let _ = app.emit("margin://open-folder", ());
        } else if let Some(index) = recent_document_menu_index(menu_id.as_ref()) {
            let _ = app.emit("margin://open-recent-document", index);
        } else if menu_id.as_ref().starts_with(CLEAR_RECENT_MENU_ITEM_PREFIX) {
            let _ = app.emit("margin://clear-recent-documents", ());
        } else if menu_id.as_ref() == "file_save" {
            let _ = app.emit("margin://save-document", ());
        } else if menu_id.as_ref() == "file_save_as" {
            let _ = app.emit("margin://save-document-as", ());
        } else if menu_id.as_ref() == "file_print" {
            let _ = app.emit("margin://print-document", ());
        } else if menu_id.as_ref() == "file_close_tab" {
            let _ = app.emit("margin://close-tab", ());
        } else if menu_id.as_ref() == "file_close_window" {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.close();
            }
        } else if menu_id.as_ref() == "window_previous_tab" {
            let _ = app.emit("margin://previous-tab", ());
        } else if menu_id.as_ref() == "window_next_tab" {
            let _ = app.emit("margin://next-tab", ());
        } else if menu_id.as_ref() == "edit_command_palette" {
            let _ = app.emit("margin://open-command-palette", ());
        } else if menu_id.as_ref() == "edit_find" {
            let _ = app.emit("margin://open-find", ());
        } else if menu_id.as_ref() == "edit_find_and_replace" {
            let _ = app.emit("margin://open-find-and-replace", ());
        } else if menu_id.as_ref() == "edit_find_next" {
            let _ = app.emit("margin://find-next", ());
        } else if menu_id.as_ref() == "edit_find_previous" {
            let _ = app.emit("margin://find-previous", ());
        } else if menu_id.as_ref() == "view_toggle_file_tree" {
            let _ = app.emit("margin://toggle-file-tree", ());
        } else if matches!(menu_id.as_ref(), "insert_comment" | "context_add_comment") {
            let _ = app.emit("margin://add-comment", ());
        } else if let Some(kind) = insert_payload(menu_id.as_ref()) {
            let _ = app.emit("margin://insert-block", kind);
        }
    });

    builder
        .invoke_handler(tauri::generate_handler![
            take_pending_open_urls,
            choose_markdown_document,
            open_markdown_document,
            choose_directory,
            read_directory_tree,
            open_native_path,
            watch_markdown_document,
            choose_markdown_save_path,
            show_comment_context_menu,
            confirm_close_tab,
            quit_app,
            print_window,
            save_markdown_document,
            read_settings,
            write_settings,
            sosein_cloud_enabled,
            start_sosein_oauth_login,
            sosein_api_request,
            check_for_app_update,
            install_app_update,
            read_recent_documents,
            write_recent_documents
        ])
        .build(tauri::generate_context!())
        .expect("failed to build Margin desktop app")
        .run(|app_handle, event| match event {
            #[cfg(any(target_os = "macos", target_os = "ios"))]
            tauri::RunEvent::Opened { urls } => {
                dispatch_native_open_urls(
                    app_handle,
                    urls.into_iter().map(|url| url.to_string()).collect(),
                );
            }
            _ => {
                #[cfg(not(any(target_os = "macos", target_os = "ios")))]
                let _ = app_handle;
            }
        });
}

#[cfg(test)]
mod settings_tests {
    use super::*;

    #[test]
    fn parses_local_user_name_from_settings() {
        let settings =
            parse_settings_toml("theme = \"dark\"\nlocal_user_name = \"Ada Lovelace\"\n");

        assert_eq!(settings.theme, "dark");
        assert_eq!(settings.local_user_name, "Ada Lovelace");
    }

    #[test]
    fn round_trips_quoted_local_user_name() {
        let settings = AppSettings {
            theme: "light".to_string(),
            local_user_name: "Ada # One".to_string(),
            sosein_cloud_enabled: true,
        };

        let parsed = parse_settings_toml(&settings_toml(&settings));

        assert_eq!(parsed.theme, "light");
        assert_eq!(parsed.local_user_name, "Ada # One");
        assert!(parsed.sosein_cloud_enabled);
    }
}
